### ISSUE TITLE
Support to run terminal scripts

### ISSUE THREAD

**Issue by dxcore35** [darlal/obsidian-switcher-plus#1]
If you add ability to run any scripts via terminal triggered in your switcher. You will be forever loved in Obsidian tech community. Similar feature have Sublime reader.

**Comment by darlal** [comment]
Thanks for the feedback. What do you see as a use-case for this feature? what would you use it for?

**Comment by dxcore35** [comment]
There is at least 50 user cases why user run the scripts.... what is problem is that that to run them the people usually do it by 3-party app, so it will differ from Mac to Windows... 

For example I run 2 scripts:
1. Script will Uppercase selected text
2. Script will fill daily note based on date of note.

If you implement this feature it will expand infinite horizons for your extension. 

Just check Sublime reader and press CMD+SHIFT+P

![Screenshot 2020-08-24 at 06 11 21](https://user-images.githubusercontent.com/7279156/90991634-b6bcb480-e5d0-11ea-84b3-1f39ed4dc605.jpg)

**Comment by liamcain** [comment]
@dxcore35 Obsidian already has a command palette (default shortcut is command + p but you can remap it to command + shift + p to match sublime text.

**Comment by dxcore35** [comment]
I know :D I know I can remap keyboard.... I post the picture not for that reason. I post it how many different features it has! Now obsidian is kind of shortcut manager thru that windows. Not mulitmanager as in Sublime. By adding ability to run script in your plugin you will allow to make those extra features in Obsidian.

**Comment by darlal** [comment]
@dxcore35 the feature you are referring to exists in the Sublime Text `Command Palette`, the VSCode `Command Palette` has a similar feature too. Obsidian also has a `Command Palette`, however the Obsidian `Command Palette` currently does not have this feature as you've pointed out. This plugin is not the Obsidian `Command Palette`, but rather, it's the Obsidian `Quick Switcher`, which is an entirely different piece of functionality, although the UI looks similar. I do think the feature you mention is useful, but it is not appropriate for the `Quick Switcher`, it belongs in the `Command Palette`.

**Comment by dxcore35** [comment]
:) OK I see now! You are right in belongs to ```Command Palette```. Your UI looks just a same!

**Comment by dxcore35** [comment]
:) OK I see now! You are right in belongs to Command Palette. Your UI looks just a same!
