### ISSUE TITLE
Respect "Default location for new notes" setting

### ISSUE THREAD

**Issue by JeppeKlitgaard** [darlal/obsidian-switcher-plus#100]
When creating a new note by holding shift in the switcher, the note should be created in the location defined by the "Default location for new notes" setting.

Currently I believe the file is always created in the root of the vault even though I have my default location set to "Same folder as current file".

**Comment by darlal** [comment]
Hey @JeppeKlitgaard I haven't been able to reproduce this. The file creation seems to respect the default location for new notes setting in both Standard and Headings mode. Some more information might help track down what's happening, what mode do you see this behavior in? and please provide the specific steps you're taking. Thanks!
