### ISSUE TITLE
Migrating from starred to bookmarks?

### ISSUE THREAD

**Issue by tonyxiao** [darlal/obsidian-switcher-plus#102]
Currently quick switcher ++ works only with starred notes, but obsidian is deprecating starred in favor of bookmarks. Let's do the same?

**Comment by darlal** [comment]
Hey @tonyxiao, for sure, this is on the radar, and coming soon. Thanks!

**Comment by fredcallaway** [comment]
It seems to me that Quick Switcher++ actually breaks with bookmarks. If I have a bookmark on "Tasks" then any search that would match Tasks (e.g. "t", "ta", or even just "s") gives an empty result list.

**Comment by tonyxiao** [comment]
This is now a bigger issue given that obsidian has completed removed starred plugin in latest release.

**Comment by fredcallaway** [comment]
D'oh! I should probably remember to check for updates before reporting bugs 😛

**Comment by darlal** [comment]
Bookmarks support is live with  [release 3.2.0](https://github.com/darlal/obsidian-switcher-plus/releases/tag/3.2.0). Thanks!
