### ISSUE TITLE
Is it possible to switch to a note that starts with `@`?

### ISSUE THREAD

**Issue by axelson** [darlal/obsidian-switcher-plus#106]
Is there a way to switch to a note that starts with a `@` without changing the default settings? I know that I could change the "Symbol list mode trigger" but if I have any conflicts with the new trigger than I'd run into the same problem.

Here's a couple ideas for how this could be worked around from a UX perspective:
- Prepending a space character searches for a literal `@` (or whatever the "Symbol list mode trigger" is set to)
- Doubling the "Symbol list mode trigger" searches for a literal character (this is similar to Postgres)
- Prepending the character with a backslash (`\`) will search for a literal character (this is similar to regexes)

**Comment by darlal** [comment]
The switcher doesn't do any escaping like that currently. One thing you could try is change the trigger character to one of the prohibited filename characters in the interim. Thanks!

**Comment by darlal** [comment]
This is live in [release 3.3.7](https://github.com/darlal/obsidian-switcher-plus/releases/tag/3.3.7), the escape character is configurable. Thanks!
