### ISSUE TITLE
[Feature Request] Quick Filters → Additional Hotkey →   `ALT/Option + Number` 

### ISSUE THREAD

**Issue by FelipeRearden** [darlal/obsidian-switcher-plus#108]
Hello @darlal !!!!!

Quick Filters is absolutely FANTASTIC!!!!

Spectacular idea that already improved my workflow.

If you dont mind I would like to suggest a tiny feature:

→  **Would be possible to add support for <kbd>ALT/Option</kbd> as hotkeys to toggle QuickFilters ?**

I am asking about this because this way I can execute the hotkey only with my left hand.

→  Using <kbd>CRTL/CMD + ALT</kbd> I have to use the right hand to select the number while holding <kbd>CRTL/CMD + ALT</kbd>

→ Using <kbd>ALT</kbd> I can do everything only with one hand :)

---

Thanks for reading this !!!!! I hope you like my suggestion 🙏 🙏 🙏

Let me know if you need more information !!!

Have a great day 🌞

**Comment by darlal** [comment]
Hey @FelipeRearden glad you're finding the new feature useful. The modifiers used to trigger Quick Filters are not modifiable via the app setting, but they are defined in the plugins `data.json` file. So by modifying the json file you could change the modifiers used. If you're comfortable editing a plain text json file, do the following:

1. Close Obsidian
2. Make a backup copy of the `data.json` file
3. Open the `data.json` file in a text editor
4. Search for the key `modifiers`, there should only be one match, which should be nested under a `quickFilters` key.
5. You'll want to modify the value of the `modifiers` array to only contain `Alt`

By default, it might look something like this:

```
   "modifiers": [
      "Ctrl",
      "Alt"
    ],
```

And when you're done, you want it to look like this:

```
 "modifiers": [
      "Alt"
    ],
```

Save the data.json file, restart Obsidian, and the new modifier should be reflected in the Quick Filters hotkey list. That should get you the behavior that you want.

**Comment by FelipeRearden** [comment]
Hello @darlal !!!!!!

Thank you very much for the newbie proof guide !!!!!!!

It worked perfect !!!! I am so happy to be able use the Quick Filters only with `Alt` !!!!!

I am gonna close this issue :)

Thank you very much and have a great day ☀️
