### ISSUE TITLE
[Feature Request] Symbol Mode → New Toggle to Cycle Between Modes from the Active Note

### ISSUE THREAD

**Issue by FelipeRearden** [darlal/obsidian-switcher-plus#109]
Hello @darlal !!!!!

I am trying to implement a new workflow with QS++ that I would like to share with you. 

In a nutshell is a new toggle inside `Symbol Mode Settings` that change the behavior when the user is **CYCLE BETWEEN** modes.

This FR is related to the **dynamic way** that the content of each **Mode** is **updated** based on the previous active mode. 

My FR is to have a toggle to **DISABLE** this behavior 

Let me try to explain ...

## My Workflow

I wanna create a way to cycle between some QS++ modes using a single hotkey. 

This is my Modes Setup:
⭘ `Standard Mode` → `empty` → Hotkey <kbd>SHIFT+'</kbd>
⭘ `Symbol` → `~` 
⭘ `Related Items` → `~~`
⭘ `Commands` → `~~~`

It's important to emphasize that when I hold <kbd>SHIFT</kbd> then hit <kbd>'</kbd> it will generate `~` in the text field.
![1158374F-49F5-4B82-B11A-901D34910A7F](https://user-images.githubusercontent.com/85180696/235728594-e65a820b-6684-4800-91ab-dd4e2289e9b0.jpeg)

This way, with this setup I can cycle between the modes only hitting <kbd>SHIFT+'</kbd>

1️⃣ <kbd>SHIFT+'</kbd> to open `Standard Mode`
2️⃣ one more <kbd>SHIFT+'</kbd> to go to `Symbol Mode`
3️⃣ again <kbd>SHIFT+'</kbd> to go to `Related Items Mode`
4️⃣ and one more <kbd>SHIFT+'</kbd> to go to `Commands Mode`

📽️ As you can see from the video below, this setup works :) By **works** I mean that I can cycle between the modes with this hotkey

[video](https://user-images.githubusercontent.com/85180696/235726729-e183a288-7f51-45c0-b58a-703977440be7.MOV)

## My Problem 

Since the QS++ modes are dynamic, when I cycle between then it will show/bring the result from the **previous mode** and NOT the result from the ACTIVE NOTE 

### Example

⭘ Active Note is `80 Toolbox/89 MetaNotes/89.01 InfoNote/InfoNotes.QN.md`

⭘ The Selected Item in Standard Mode is the Note `007.md` 
![F85E0423-2521-47D3-AC0D-6C7A1674B675](https://user-images.githubusercontent.com/85180696/235727106-8fe8fe55-e242-415f-bdb7-de44bbe2c43a.jpeg)

⭘ When I hit <kbd>SHIFT+'</kbd> to go to Symbol Mode it will bring me the result from `007.md` and not from my active note → THIS IS MY FR !!!!!

The blue border show the headings from `007.md` :(
![D5691BC8-8EDB-4FE5-ACD5-F76D7F192D15](https://user-images.githubusercontent.com/85180696/235727232-740569e8-5cb6-48e7-8746-33ad951207df.jpeg)

⭘ So I continue my journey and hit <kbd>SHIFT+'</kbd> to go to `Related Items Mode` . The Result is from the Active Note and not from `007.md` → It is working perfect for this workflow. 

The red border show the related items from the Active Note :)
![862643A7-58D4-4E68-B32B-72F8EAC0792F](https://user-images.githubusercontent.com/85180696/235727293-e5901e0f-a20b-4b6b-9b77-0a83135648a4.jpeg)

---

## In a Nutshell 

To summarize my FR is a toggle to disable the `Symbol Mode` to get information/input from the QS++ open modal and always get information/input from the active note.

If there is no active note, do exactly what is doing today. 

## Why You need this Feature?

This is important to me because I can easily and fast cycle between command palette, recent files, files related to the active file and the content of the active file (heading, tags, callouts and backlinks) with a SINGLE command using my left hand :)

This saves me a lot of time because this actions are the most repeated actions that I perform daily inside Obsidian :) 

As you can see from the image, I changed the style of my modals to let me see the content to let me see the workspace. I did this to do a fast switch without losing focus on the task and lose attention. 

---

Thanks for reading this !!!!! I hope you like my suggestion 🙏 🙏 🙏

Let me know if you need more information !!!

Have a great day 🌞

**Comment by darlal** [comment]
Hey @FelipeRearden thanks for the detailed post. I think what may be useful here is a command that always triggers symbols for the active editor. With that you could setup your hotkey sequence to work in a predictably against the active editor. This would likely be necessary for related items as well.

A few other comments:

- This dynamic capability of being able to operate on previous results is by design. It brings a lot of power to Switcher++, like saving you from having to open every file in an active editor just to access some information about it.
- The way related items is working in your sequence is largely accidental. Related items doesn't operate on symbol suggestions, so it's falling back to the active editor because in your sequence the previous results symbols, which is why it's behaving the way you want.

**Comment by FelipeRearden** [comment]
Hello @darlal !!!!

Thank you very much for the reply :)

> Hey @FelipeRearden thanks for the detailed post. I think what may be useful here is a command that always triggers symbols for the active editor. With that you could setup your hotkey sequence to work in predictably against the active editor.

100% agree @darlal ! That's exactly what I was trying to say. I am glad that we get the same conclusion and that you could understood my workflow.

> This would likely be necessary for related items as well.

You are right @darlal ! Both modes has the same dynamic feature that hurts this workflow. 

> * This dynamic capability of being able to operate on previous results is by design. It brings a lot of power to Switcher++, like saving you from having to open every file in an active editor just to access some information about it.

The dynamic capability is amazing and a great feature of QS++ that should be the main feature !!!!!! 

My FR is about expanding the set of workflows of QS++ with a toggle option/setting that changes the behavior. this way we can have both methodologies to let the user decide :)

> * The way related items is working in your sequence is largely accidental. Related items doesn't operate on symbol suggestions, so it's falling back to the active editor because in your sequence the previous results symbols, which is why it's behaving the way you want.

Thank you and you are absolutely right ! We need the same treatment for related items as well and not only Symbol Mode.

I was waiting for you reply to say this to you about Related items. You are so amazing that you could understand exactly what I was describing in my FR and correct the wrong part :)

---

Thank you very much and have a great day ☀️



---

**Comment by darlal** [comment]
This is live in [release 3.3.1](https://github.com/darlal/obsidian-switcher-plus/releases/tag/3.3.1). Thanks!

**Comment by FelipeRearden** [comment]
> This is live in [release 3.3.1](https://github.com/darlal/obsidian-switcher-plus/releases/tag/3.3.1). Thanks!

Hello @darlal !!!!!

Thank you very much for this !!!! It is working perfect !!!!!!!!

I really like the way that you add this feature: creating new text fields for dealing exclusive with the Active Note was a smart idea !!!! This way we can create multiple workflows surrounded by Related Items and Symbol Mode :)

Thank you very much and have a great day ☀️
