### ISSUE TITLE
Switch Workspaces

### ISSUE THREAD

**Issue by geoffreysflaminglasersword** [darlal/obsidian-switcher-plus#11]
How hard would it be to allow a feature like 'edt' but for workspaces? e.g. 'wsp' or 'wk'
it's easy enough to assign a hotkey to 'load workspace' but I'm hoping to unify all my searching hotkeys as much as possible

**Comment by darlal** [comment]
Interesting. Adding the command itself wouldn't be difficult. Will have to see if the capability to switch workspaces is exposed in the current API.

**Comment by darlal** [comment]
@geoffreysflaminglasersword this capability is live in the latest [release](https://github.com/darlal/obsidian-switcher-plus/releases/tag/1.0.0).
