### ISSUE TITLE
BUG: Hotkey filter

### ISSUE THREAD

**Issue by marblewraith** [darlal/obsidian-switcher-plus#110]
As of the 1.2 Obsidian release, they've added the ability to filter hotkeys, the criteria being :

- All
- Assigned
- Assigned by me
- Unassigned

QuickSwitcher++ does not respect this filter.

https://user-images.githubusercontent.com/45786628/235817255-3c2e315f-db64-4eb9-94ed-405d3d706116.mp4

**Comment by darlal** [comment]
Hey @marblewraith taking a quick look at my own vault, it looks like this behavior happens with many of the plugins that expose global commands. I can't tell if it's some weirdness with they way that Obsidian is filtering the list. There doesn't appear to be a way for plugins themselves to really control this directly, as you can see [here](https://github.com/darlal/obsidian-switcher-plus/blob/master/src/main.ts#L94) Switcher++ does not register any hotkeys by default.

The same behavior happens with many of the other plugins I have installed as well, here's a screenshot of Pane Relief for example. I'd recommend opening an issue in the Obsidian forum. Thanks.

<img width="788" alt="image" src="https://user-images.githubusercontent.com/5191776/236620587-07a63bd0-d2a4-4a19-b6a3-42ed0d129b02.png">

**Comment by marblewraith** [comment]
I notice that when i do *not* filter the list.

Commands that do not have hotkeys assigned, have the word `Blank` next to them. Quick Switcher++ is the only one that does not, which is why it stood out so much.

When the list is filtered all entries with the `Blank` word are hidden. Quick Switcher ++ is not. I don't think that's a coincidence.

> as you can see [here](https://github.com/darlal/obsidian-switcher-plus/blob/master/src/main.ts?rgh-link-date=2023-05-06T11%3A12%3A48Z#L94) Switcher++ does not register any hotkeys by default.

So maybe that's the problem?

Obsidian's API has it's own default value (`Blank`), but it doesn't seem to be accounting for if you pass an empty array / null value i.e. there's no check / default override for that case.

For example, take a look at the [Footnotes Shortcut plugin](https://github.com/MichaBrugger/obsidian-footnotes/blob/master/main.ts) which i am using, and have confirmed *is being filtered correctly* in the hotkey list.

It has 2 commands that can be bound to hotkeys, neither of which is by default (lines 24 - 44).

The difference is immediately apparent. While it does pass an object with `id`, `name`, `icon`, and `checkCallback` keys.

It completely *omits* the `hotkeys` key.

**Comment by darlal** [comment]
Thanks for the additional info, I will take a look at this.

**Comment by darlal** [comment]
This has been updated in  [3.3.0 release](https://github.com/darlal/obsidian-switcher-plus/releases/tag/3.3.0). Thanks for the pointer!
