### ISSUE TITLE
FR: Place Cursor Before Callout When Selecting

### ISSUE THREAD

**Issue by julroger2013** [darlal/obsidian-switcher-plus#111]
It's very useful being able to select headings, callouts, embeds, etc. in the @ symbol mode. 

Can I suggest a very modest tweak? When selecting a callout (and perhaps embeds, too), would it be possible to have the cursor move to the line immediately *before* the callout when hitting enter? 

I suggest this because, currently, the entire callout is selected. In Live Preview mode, this has the effect of causing the callout to un-render, instead showing the underlying markdown. Since one of the benefits of callouts is being able to collapse them to hide larger blocks of content—in my case, helpful dataview queries—I have to navigate the cursor out of the callout's underlying markdown before I can access the information in the callout. 

Placing the cursor on the line immediately prior to the callout would make it easier to quickly view the callout in its rendered view. 

That said, it only takes one "arrow up" command to get out of the callout's markdown, so this is not a pressing need by any means.

**Comment by darlal** [comment]
The same is true for headers/links/etc.. Sometime you want to navigate to "edit" the symbol, in which case this behavior is good, sometimes you want to just "view" the symbol in which case Obsidian dropping into edit mode is not what you want. The effect on callouts is just more pronounced than the others. I'm afraid the change you're proposing would just then become annoying for the "edit" use-case. But I'm not sure what the right answer is here though.

**Comment by julroger2013** [comment]
Fair point. I think it's probably best to leave the existing functionality in place. Arrowing up the cursor by one line is not significantly inconvenient, and changing it would come at the cost of desired function in other contexts, I am sure.

**Comment by darlal** [comment]
Yea, I tend to agree. Thanks!
