### ISSUE TITLE
[Feature Request] Option to hide or place bookmarks to the bottom of the quickswitcher.

### ISSUE THREAD

**Issue by IRIS-CORE** [darlal/obsidian-switcher-plus#112]

**Comment by darlal** [comment]
Bookmarks don't appear in the custom Headings  mode at all, so you won't see them if you use that mode. In the standard mode, there isn't really a way to filter all of them out, however non-file bookmarks (like searches, and folders, etc) could be filtered out.

**Comment by darlal** [comment]
Release [3.3.5](https://github.com/darlal/obsidian-switcher-plus/releases/tag/3.3.5) introduces bookmarks in `Headings Mode` with an option to disable.
