### ISSUE TITLE
[Feature Request] Pressing backspace when the input field is empty closes the quick switcher

### ISSUE THREAD

**Issue by Jack-Chronicle** [darlal/obsidian-switcher-plus#113]
Using the plugin on my tablet, whenever i press escape it still closes the input field but it also goes back a page which can get annoying. 

It would be great if you could add an option to let users press backspace to close it as well, similar to how the "better command palette" plugin works

**Comment by darlal** [comment]
> it still closes the input field but it also goes back a page

I'm not sure I understand what you're referring to here, could you elaborate?

> add an option to let users press backspace to close it as well

This can be added pretty easily. Thanks!

**Comment by Jack-Chronicle** [comment]
On mobile, the escape button on a keyboard also works as a back button
And when pressing escape to close the quick Switcher, it goes to the previous page as well as closing it

**Comment by darlal** [comment]
This is live in [release 3.3.2](https://github.com/darlal/obsidian-switcher-plus/releases/tag/3.3.2). Thanks!
