### ISSUE TITLE
[Feature Request] Sort the edt menu after most recently accessed.

### ISSUE THREAD

**Issue by johannesCmayer** [darlal/obsidian-switcher-plus#114]
Instead of sorting the edt menu after the order, the tabs are arranged, order them based on the last access time of that tab. Ideally, this would be a new, command in quickswitcher++ that can be assigned to an initial string you can type, e.g. edto, such that you can choose which behavior you want.

**Comment by darlal** [comment]
Thanks for the feature request. Likely a new setting could be added to enable this behavior for `Editor mode` rather than creating a whole new mode.

**Comment by darlal** [comment]
This is live in [release 3.3.2](https://github.com/darlal/obsidian-switcher-plus/releases/tag/3.3.2). Thanks!
