### ISSUE TITLE
[Feature request] Ability to set number of items shown

### ISSUE THREAD

**Issue by johannesCmayer** [darlal/obsidian-switcher-plus#116]
I would like to have the ability to increase the number of items that the quick switcher shows. I think this would be especially useful for me when I open the quick switcher without any input to just see and switch to the recently opened documents. 

Ideally, I would also have the ability to only show recently opened files as long as I haven't entered anything into the quick switcher.

**Comment by darlal** [comment]
> the ability to increase the number of items that the quick switcher shows 

Obsidian used to only track at most 10 recent files, Switcher++ always display all 10. I'll have to see if Obsidian is now tracking more than just 10, in which case we would be able to increase that number as well.

> Ideally, I would also have the ability to only show recently opened files as long as I haven't entered anything into the quick switcher.

`Headings mode` currently displays the recently open files when there is no search term. I'm not sure if you're asking for something different here.

**Comment by darlal** [comment]
Looks like Obsidian did increase the number of recent files it tracks. This is now reflected in Switcher++ with a new setting to customize. This is live in [release 3.3.2](https://github.com/darlal/obsidian-switcher-plus/releases/tag/3.3.2). Thanks!
