### ISSUE TITLE
[Bug] Switching within Sidebar Note

### ISSUE THREAD

**Issue by julroger2013** [darlal/obsidian-switcher-plus#118]
I've noticed what I *think* is a small bug. When attempting to use the default Switcher++ mode within a note open in the sidebar, the selected note opens in the middle panel, rather than in the sidebar. I suspect this is because the Switcher++ modal removes focus from the sidebar, and Obsidian therefore defaults to opening in the middle pane—but that's just my guess. 

I'm not sure whether this is a bug or intended functioning, but it doesn't seem to happen with the built-in Obsidian Quick Switcher. 

The plugin is otherwise working perfectly, and the extra features it adds continue to be amazing! Thank you for all your work.

**Comment by darlal** [comment]
Hey @julroger2013 taking a look at this, I think Switcher++ may be behaving as expected depending on your settings. For Switcher++ there are a couple settings that can change this behavior.

**Standard mode**
This mode _is the system switcher_ (not a re-implementation), however some custom settings allow you to change some behaviors. If the `override standard mode` setting is disabled then you should see the system switcher behavior. If that setting is enabled then see below.

**Custom modes**
In the custom modes , like `Headings modes`, the `Default to open in new tab` will change this behavior. If that setting is disabled, then you should see the system switcher behavior. If that setting is enabled, then a new tab will always be opened in the middle panel. 

So, please take a look at your settings. You can quickly disable both `override standard mode` and `Default to open in new tab` and it should behave the same as the system switcher. With either of the settings enabled, then the behavior will change accordingly. 

Let me know if you're seeing something different. Thanks!

**Comment by julroger2013** [comment]
You landed right on the issue! Turns out I had the "Default to open in new tab behavior" toggled on, which was indeed attempting to open things in the middle panel. I've turned that setting off and things now work exactly as I would expect.

Thanks, as always, for your help and guidance.

**Comment by darlal** [comment]
Awesome! Glad it's figured out.
