### ISSUE TITLE
Feature Request: More customizable sort order adjustments

### ISSUE THREAD

**Issue by axelson** [darlal/obsidian-switcher-plus#121]
For my structure notes/MOC I prefix their name with a `@` (e.g. `@Programming` and `@Obsidian`) and when using the quick switcher I'd like to prioritize those notes over other notes but currently if I search for `obsid` then I'll get notes like `Obsidian Plugin Ideas` and `Obsidian Learning Tips` _before_ `@Obsidian` but I'd like `@Obsidian` to be ranked higher than `Obsidian Plugin Ideas` even though the first 4 characters are a direct match.

There's a few ways that I could see this being implemented (and I'm sure you may have others!):
- Add a new Result priority adjustment that asks for a character (in my case `@`) and if the note starts with that character then it will get a boost (or downrank if that's what the user set)
    - This might be very specific to how I'm creating my notes
- In the Quick Switcher++ settings add a setting that allows you to create your own inline Result priority adjustment
    - The setting would allow you to define a function that receives the note metadata and either returns a boolean indicating if the note matches this "type", or the function could return the adjustment directly (but then we'd need to remove the slider for this Result priority adjustment)
- Make it possible for other plugins to register their own Result priority adjustment categories
    - This is similar to the previous option but requires creating a plugin rather than an anonymous function inside the configuration

Thanks for making Quick Switcher++! It's an invaluable part of my Obsidian workflow!

Edit: another result priority adjustment I would like to make is for attachments (especially excalidraw files)

**Comment by darlal** [comment]
Thanks for the feature request. Allowing for completely custom priority adjustment via plugin or custom functions would require some new infrastructure. This would likely be a longer term feature request.

Adding an adjustment that could be applied to all attachment file types is more straightforward and could be done sooner.

**Comment by axelson** [comment]
Makes sense. Either would be appreciated! 😃

**Comment by darlal** [comment]
Attachment file types is available in [release 3.3.9](https://github.com/darlal/obsidian-switcher-plus/releases/tag/3.3.9). Thanks!

**Comment by axelson** [comment]
Thank you! ❤️
