### ISSUE TITLE
Press number keys 1,2,3,..,9 to select items

### ISSUE THREAD

**Issue by maggaou** [darlal/obsidian-switcher-plus#124]
For example in Bookmarks mode one could press 2 to directly open the second item in the list. Obviously when this feature is enabled, one cannot perform filtered search if the query includes numbers (see details below).

Other special cases:
If numbers are used in toggle symbols for different modes, prioritize this behavior. 

If filtered search is used, select these results using numbers 1,2,3,..,9 (OR) If filtered search is used, then this feature is disabled.

If restore previous input is on, it should work similarly as doing filtered search and then pressing number to select item.

In addition display number icons (possibly using different color than list items) next to list items to indicate the feature (or to indicate that the feature is on, if not enabled by default).

**Comment by darlal** [comment]
Thanks for the feature request. If I understand correctly the feature is to enable selection of items 1-9 in the result list using a hotkey, you're proposing number keys 1-9. Let me know if I've miss understood the request.

As you've pointed out, using these hotkeys by themselves will interfere with regular typing. One way to work around this is to use a modifier key, so for example  `cmd/ctrl` modifier plus the number key.

>If numbers are used in toggle symbols for different modes, prioritize this behavior.
>f filtered search is used, select these results using numbers 1,2,3,..,9 (OR) If filtered search is used, then this feature is disabled.

Both of these become non-issues with modifier key plus number key.

>If restore previous input is on, it should work similarly as doing filtered search and then pressing number to select item.

I'm not sure follow this one. Do you mean it should behave the same way as you described above in the "filtered search" paragraph, or do you mean the switcher should auto-select the previous selection again, which could be very confusing.

**Comment by darlal** [comment]
[Release 4.5.1](https://github.com/darlal/obsidian-switcher-plus/releases/tag/4.5.1) added quick selection hotkeys. These use modifier+key combination by default, there is no special handling for single digit numkeys. However, the hotkey combination can be changed by modifying the `data.json` settings files directly. Thanks!
