### ISSUE TITLE
[BUG?] New files are not opened in new tab.

### ISSUE THREAD

**Issue by antoKeinanen** [darlal/obsidian-switcher-plus#125]
When creating a new file with shift+enter the new file is opened in the last active tab and not in a new tab even if `Default to open in new tab` is enabled in the settings. Is this intended behavior? If you just press enter on a file that does not exist it creates a new file in a new tab.

**Comment by darlal** [comment]
Thanks for the report, will take a look.

**Comment by darlal** [comment]
In `Headings Mode` `shift+enter` should create a new tab if the `Default to open in new tab` is enabled, if it's not enabled, then `cmd+shift+enter` will also open in a new tab.

`Standard Mode` is the default out of the box Obsidian switcher, so in that case Obsidian handles the create event directly - Obsidian doesn't know about the `Default to open in new tab` setting. Obsidian uses `shift+enter` to create in existing tab, and `cmd+shift+enter` to create in new tab. This is behaving as expected, thanks!

**Comment by Mobbbb** [comment]
> In `Headings Mode` `shift+enter` should create a new tab if the `Default to open in new tab` is enabled, if it's not enabled, then `cmd+shift+enter` will also open in a new tab.
> 
> `Standard Mode` is the default out of the box Obsidian switcher, so in that case Obsidian handles the create event directly - Obsidian doesn't know about the `Default to open in new tab` setting. Obsidian uses `shift+enter` to create in existing tab, and `cmd+shift+enter` to create in new tab. This is behaving as expected, thanks!

sorry,I also had this problem.But I can't understand your explain.Maybe, you could tell me what should I do to make `Default to open in new tab` works normally.
