### ISSUE TITLE
[Feature request] Folder filter

### ISSUE THREAD

**Issue by RenanSantos7** [darlal/obsidian-switcher-plus#126]
This plugin could make it possible to filter items based on their location.

This would be useful, for example, to remove templates from the search, which personally bothers me a bit.

**Comment by RyotaUshio** [comment]
There is the "exclude folders" option already. I think it is what you want.

**Comment by darlal** [comment]
@RenanSantos7 the `Exclude folders` [setting](https://github.com/darlal/obsidian-switcher-plus#search-headings-configuration) as @RyotaUshio mentioned in `Heading Mode` will enable you to hide folders in searches for that mode. Thanks!

**Comment by darlal** [comment]
The `Exclude folders` regex is only applied when in [Headings Mode](https://github.com/darlal/obsidian-switcher-plus#search-headings-configuration). The screenshots you posted seem to be in `Standard Mode`, so the regex would not be applied.

**Comment by RenanSantos7** [comment]
> The `Exclude folders` regex is only applied when in [Headings Mode](https://github.com/darlal/obsidian-switcher-plus#search-headings-configuration). The screenshots you posted seem to be in `Standard Mode`, so the regex would not be applied.

This is the case. The plugin doesn't have a folder filter to `Standard Mode`, just to `Headings Mode`.
