### ISSUE TITLE
how to search regardless of the order of the words

### ISSUE THREAD

**Issue by qiaoxingxing** [darlal/obsidian-switcher-plus#128]
There is a file named "flashcard obsidian.md."
I can find the file by searching for "flash ob,"
but I cannot find it by searching for "ob flash."

Sometimes, I can't remember the exact name of the note. How can I search for a note whose name contains both "a" and "b", regardless of the order of the words.

**Comment by darlal** [comment]
Hey @qiaoxingxing this has come up before (see discussion #31), Switcher++ uses the builtin Obsidian searching algorithm which has this restriction. There is an open  [Obsidian feature request](https://forum.obsidian.md/t/remove-strict-word-order-requirement-in-quick-switcher-and-link-suggestions/10966) for this in the Obsidian forum, I would recommend upvoting that request as well. In the near term, Switcher++ likely will continue to use the Obsidian algorithm.

As an alternative, I think the plugin [Another Quick Switcher](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher) may have this (I'm not entirely sure).

**Comment by qiaoxingxing** [comment]
@darlal  Thanks for your reply and recommendation. I'd like to upvote that request.
