### ISSUE TITLE
Additional settings to customize the commands syntax

### ISSUE THREAD

**Issue by lyndhurst** [darlal/obsidian-switcher-plus#13]
Hi,
I was wondering if it could be possible to add some settings to customize the `@` and `edt` commands. Personally, I am fine with `@` syntax, especially since it matches the VsCode keybindings :)

Nevertheless, I would like to limit the number of keyboard shortcuts in obsidian, and a shorter command than `edt` like `+` or `>` for example would reduce the cost of switching between open editors imho (I tend to have quite a few opened simulteanously). This way for a very small additional effort (one extra character prefix to the search), I could have access to 'open editors search', 'symbol search', and 'files in vault search' with only one keyboard shortcut.

To push the logic even further, I feel that switching between open editors is a task I need to execute even faster than opening another file from the vault. What I mean is that usually if I have many editors open, it is because they belong to the same work / thought process, and in that case I would rather keep a fluid workflow switching seamlessly between editors. On the other hand, when I search for another file, I usually am looking for additional resources, and kind of "out of the zone" anyway so I do not mind typing extra stuff. So, following that logic, I think I would even prefer having the default search (no extra `@` or `edt` command) for switching between open buffers, and a special command to search for files in the vault instead.

Sorry if I was too long sharing my thoughts, but I feel this kind of flexibility could add value to your (already very useful) plugin. Thanks for your time and attention :)

**Comment by whitenoisedev** [comment]
In short, I agree I would like something shorter than edt.
Letting the user customize the trigger characters would be a nice enhancement.
Thanks for your work.

**Comment by darlal** [comment]
Thanks for the report. I'll add it to the list.

> I think I would even prefer having the default search (no extra @ or edt command) for switching between open buffers, and a special command to search for files in the vault instead.

@lyndhurst one thing you could do for this, is setup the hotkey that opens the switcher to open in Editor mode by default. Switcher++ exposes commands for each mode.

**Comment by lyndhurst** [comment]
> @lyndhurst one thing you could do for this, is setup the hotkey that opens the switcher to open in Editor mode by default. Switcher++ exposes commands for each mode.

Thanks for the tip @darlal , I did end up setting my shortcuts this way, and it has improved my workflow, thank you.

**Comment by darlal** [comment]
@lyndhurst @WhiteNoiseDev the latest [version](https://github.com/darlal/obsidian-switcher-plus/releases/tag/0.0.12) of the plugin will allow you to customize the plugin trigger characters via settings. Will work with 12.5 but not 12.7 (yet).

I will close this issue out. Thanks!

**Comment by lyndhurst** [comment]
Thanks for the update, I will be trying this out soon.
