### ISSUE TITLE
[BUG] "Default open in new tab" is adding notes to mobile sidebar

### ISSUE THREAD

**Issue by csss1234** [darlal/obsidian-switcher-plus#130]
I believe QS++ is causing this issue https://forum.obsidian.md/t/bug-notes-showing-and-getting-stuck-in-sidebars-left-or-right/47150/6

I like the "new tab" option OFF, on mobile. One tab is plenty.

For me this keeps happening on the left sidebar on mobile. I think it is only in conjunction with some other plugins like opening notes through Advanced URI. But it is happening daily.

**Comment by darlal** [comment]
Interesting.. happy to help figure out what might be happening here. In your specific case how does QS++ fit into the workflow when the issue occurs?

- Do you see this on iOS or Android? Also, is it a tablet, or smaller (phone) screen?
- Are there any steps that you can share for how to reproduce this?
