### ISSUE TITLE
[Feature Request] Ignore search word order

### ISSUE THREAD

**Issue by doit132** [darlal/obsidian-switcher-plus#131]
# Request Description

When I input two words, I want the matching process to be done not in word order. 

For example, I have two files, one with the name `hello world` and the other with the name `world hello`. When I enter the `hello world` search term, I want both files to be displayed

**Comment by darlal** [comment]
Hey @doit132 this has come up before (see discussion #31), Switcher++ uses the builtin Obsidian searching algorithm which has this restriction. There is an open [Obsidian feature request](https://forum.obsidian.md/t/remove-strict-word-order-requirement-in-quick-switcher-and-link-suggestions/10966) for this in the Obsidian forum, I would recommend commenting on that request. 

In the near term, Switcher++ will continue to use the Obsidian algorithm. As an alternative, I think the plugin [Another Quick Switcher](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher) may have this (I'm not entirely sure).
