### ISSUE TITLE
[Feature Request] Shortcut to copy to clipboard instead of open

### ISSUE THREAD

**Issue by terheyden** [darlal/obsidian-switcher-plus#132]
In Quick Switcher++ you can interact with the selected note in a few useful ways, such as [Enter] to open, [Cmd-Enter] open in new tab, etc.

### Problem Description
Sometimes I'm using another plugin or app, but that plugin / app doesn't autocomplete the names of notes in my vault, so I need to use Quick Switcher++ to find notes by name, so for example:
- Activate Quick Switcher++
- Look for the note I'm interested in
- Open the note
- Copy the note name
- Go back to (other place)
- Paste in e.g. `[[My Note Name]]`

### The Feature Request
- Activate Quick Switcher++
- Look for the note I'm interested in
- Hit e.g. `Cmd-C` in the Quick Switcher++ dialog to copy the name of the selected note to the system clipboard
- Hit e.g. `Cmd-Opt-C` to copy the full path of the selected note to the system clipboard

Thank you!!! ❤️ I love this plugin.

**Comment by darlal** [comment]
Hey, glad you're finding the plugin useful.

This FR sounds very similar to the existing `Insert link in editor` feature, except the FR proposes accomplishing it through clipboard instead. `Insert link in editor` can be configured in the "General settings" section of the settings pane. If you're wanting to paste within Obsidian, I think that should work for you (the last step in your workflow `Paste in e.g. [[My Note Name]]` makes me think that may be the case). However if `Go back to (other place)` in your workflow is outside of Obsidian then I could see wanting to use the clipboard.
