### ISSUE TITLE
Headings Mode Question? / Feature Request?

### ISSUE THREAD

**Issue by marblewraith** [darlal/obsidian-switcher-plus#133]
## Problem

This will take a bit of explaining.

Good file naming conventions should be “web safe” meaning only alpha-numerals, underscores, and hyphens, should be used in file names.

This is to avoid things like incompatibilities with charsets in different OS / programs, weird tokenization issues in the terminal, or having to do things like [percent encoding](https://en.wikipedia.org/wiki/Percent-encoding) for URL’s when sharing files.

This also means the title *verbatim* (punctuation, special chars, spacing, etc.) cannot be preserved through the file name alone, even though this is desirable for the purposes of accuracy / search / recall.

The way this is commonly addressed is with a popular plugin called [Linter](https://github.com/platers/obsidian-linter). It has [the option](https://platers.github.io/obsidian-linter/settings/yaml-rules/#yaml-title-alias) to automatically alias the H1 heading of every note by default and keep it in sync. Hence the note title verbatim can be preserved and indexed via aliases for quick switcher.

The issue being, this means *all* quick switcher++ standard mode matches have a duplicate entry. It displays both the “web safe” note (file)name and also the alias entry.

## Headings Mode

I considered using headings mode to achieve what i want. Because the headings mode matches directly on the H1 headings of notes, and be no need to use Linter to make them an alias.

But there’s a problem which prevents me from using it. Performance:

> Quick Switcher only searches the index of note names and aliases. Search searches every word in every note, which is a bigger task. — [Obsidian forums](https://forum.obsidian.md/t/slow-search-yet-fast-quick-switcher-for-large-vault-why/62969)

I’m reasonably certain headings mode uses Obsidian search (highlights the h1 heading in the same way). Which means if i’m relying on headings mode, as my vault scales out, the more notes i make, the slower search will get. 

The only way this *would not* happen is if Quick Switcher++ implemented a hash map internally, that indexes headings similar to how Obsidian indexes on note names and aliases. ***Is this the case?***

If not…

## Feature Request: Standard Mode Toggle note name results

The ability to completely hide note filename results from the standard mode results, meaning only aliases should be returned, solves the issue of duplicates.

**Comment by darlal** [comment]
Hi there!

> I’m reasonably certain headings mode uses Obsidian search (highlights the h1 heading in the same way)

This is incorrect, QSP++ does not use the search feature in headings mode. QSP++ uses an Obsidian managed metadata index that contains Headings information, here's the [implementation](https://github.com/darlal/obsidian-switcher-plus/blob/master/src/Handlers/headingsHandler.ts#L354).

>The ability to completely hide note filename results from the standard mode results

`Standard Mode` _is_ the built-in Obsidian implementation. There is no plan to change that behavior. `Headings Mode` already provides a number of settings to control the result set that you might want to take a look at.

Thanks!

**Comment by marblewraith** [comment]
Thank you for the quick response and correcting my understanding.

Are you aware of any performance between headings mode and standard mode? Meaning is there any significant performance differences between the indexes?

If not, then i will gladly make headings mode the default in all vaults going forward! 😁

**Comment by darlal** [comment]
Glad you came across that vault. Here's a bit more context about the delay you're seeing.

Searching in Headings mode is "debounced" until you are "done" typing to avoid trigerring a potentially expensive vault wide search while you're actively typing each character of the search term [source](https://github.com/darlal/obsidian-switcher-plus/blob/master/src/switcherPlus/modeHandler.ts#L190). A long enough [delay](https://github.com/darlal/obsidian-switcher-plus/blob/master/src/settings/switcherPlusSettings.ts#L45) between keystrokes is interpreted as "done typing" and the search is kicked off. 

In your testing, it probably seemed super obvious that there's a delay as you typed each character, but in practice, when you're typing normally, there will not be a delay for each character. Also, `headingsSearchDebounceMilli` (the delay time in milliseconds) is exposed in the settings file (though not in the Settings UI) so you can change the value if you like - though honestly I don't recommend it.
