### ISSUE TITLE
Improvement: "workspace" is sorted alphabetically.

### ISSUE THREAD

**Issue by kickTiger** [darlal/obsidian-switcher-plus#134]
Thank you very much for your plugin; it's the one I use most in my daily work.

I have a small suggestion that I hope you could consider:

Issue:
When I input "+" and the "workspace" appears, the list of "workspaces" that comes up is not sorted alphabetically or by characters.

Request:
I would appreciate it if, in the list of "workspaces," you could arrange them in alphabetical or character order. It would be great if this sorting could also apply to non-English characters, such as Simplified Chinese.

Once again, I want to express my gratitude for your excellent plugin.

**Comment by darlal** [comment]
Thanks for the feature request, I can definitely look into this.

**Comment by darlal** [comment]
The workspace list should be sorted now when there is no search term as of [release 3.3.8](https://github.com/darlal/obsidian-switcher-plus/releases/tag/3.3.8). Thanks!
