### ISSUE TITLE
[BUG] Default to open in new tab

### ISSUE THREAD

**Issue by Mobbbb** [darlal/obsidian-switcher-plus#136]
`Default to open in new tab` seems like didn't work.
Obsidian version is v1.4.16
Quick switcher ++ version is v3.3.8
I just install Obsidian.And install only one plugin——```Quick switcher ++```.By the default setting, ```Default to open in new tab``` is enabled.But when I click files in left menu, latest opened file is still covered by current opened file,rather than open in new tab

**Comment by darlal** [comment]
> But when I click files in left menu, latest opened file is still covered by current opened file,rather than open in new tab

Switcher++ settings to not affect the left menu/pane. The setting only applies to opening files from Switcher++ itself, and specifically when using the custom switcher modes. That setting is not expected to affect any other default Obsidian behaviors.

**Comment by Mobbbb** [comment]
> > But when I click files in left menu, latest opened file is still covered by current opened file,rather than open in new tab
> 
> Switcher++ settings do not affect the left menu/pane behavior. The setting only applies to opening files from Switcher++ itself, and specifically when using the custom Switcher++ modes. That setting is not expected to affect any other default Obsidian behaviors.

Thanks, there seems to be something wrong with my understanding
