### ISSUE TITLE
Strip diacritics when seraching

### ISSUE THREAD

**Issue by KraXen72** [darlal/obsidian-switcher-plus#139]
Please add an option to strip the diacritics (both ways) when searching:
- Searching `Slovenska` would find `Slovenská Literatúra`
- Searching `Slovenská` would find `Slovenska Literatura`
Omnisearch has this functionality, but i prefer quick switcher++ when switching between files.

**Comment by darlal** [comment]
Hey, this has come up before (see discussion #78), Switcher++ uses the builtin Obsidian searching algorithm which has this restriction. There is an open  [Obsidian feature request](https://forum.obsidian.md/t/ignore-accents-diacritics-in-search/1655/55) for this in the Obsidian forum, I would recommend commenting on that request. 

In the near term, Switcher++ will continue to use the Obsidian algorithm. As an alternative, I think the plugin [Another Quick Switcher](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher) may have this feature (I'm not entirely sure).
