### ISSUE TITLE
Command List Mode - Easily Add Hotkey

### ISSUE THREAD

**Issue by zaiquiriw** [darlal/obsidian-switcher-plus#141]
# Fantastic - Command List Enhancement?
I've only just downloaded the plugin 10 minutes ago, and it's of course an improvement on the normal quick switcher. 

I've remembered that one of the features I've always wanted (in any software) was an easy way to add hotkeys to commands as I use them. 

Within quick switcher, could I be able to hold a modifier key (`ctrl+enter`) to open the hotkey menu of the selected command (instead of triggering the hotkey). That way I can easily configure a hotkey. I could then easily hit `esc` and try out the new hotkey

This is not necessary at all, and I would add this if I had the know how. I figured I would post the thought.

**Comment by darlal** [comment]
Glad you're finding the plugin useful. Thanks for the suggestion! I'll add it to the list and see about interest.

**Comment by jose-elias-alvarez** [comment]
I believe [hotkey-helper](https://github.com/pjeby/hotkey-helper) has this feature if anyone's interested in using that as an example for an implementation.

**Comment by darlal** [comment]
This is live in [release 4.4.0](https://github.com/darlal/obsidian-switcher-plus/releases/tag/4.4.0). Thanks!
