### ISSUE TITLE
Mobile "Override standard mode behavior"

### ISSUE THREAD

**Issue by Anarchtism** [darlal/obsidian-switcher-plus#143]
Not sure if this is a feature request or a bug report. The plus button on the bottom bar on mobile (⊕) doesn't launch Quick Switcher++. Neither does the "go to file" or "see recent files" button on the new tab page.

**Comment by darlal** [comment]
Thanks for the feature request. The switcher does not currently override those buttons. I agree it would be useful to override the mobile plus button in particular. I'll add this to the backlog. Thanks!

**Comment by darlal** [comment]
With release [4.2.0](https://github.com/darlal/obsidian-switcher-plus/releases/tag/4.2.0) the "⊕" button can be configured to launch Switcher++. The new tab page buttons may be added later. Thanks!
