### ISSUE TITLE
[Feature Request] Jump to block identifier

### ISSUE THREAD

**Issue by Merlin04** [darlal/obsidian-switcher-plus#144]
It would be really nice if I could quickly find/jump to a block with a given identifier from the quick switcher - if I label something like

```md
lorem ipsum something something something ^test
```

I'd like to be able to open the quick switcher and type `^test` to search for that block.

**Comment by darlal** [comment]
Thanks for the suggestion. [Symbol Mode](https://github.com/darlal/obsidian-switcher-plus?tab=readme-ov-file#symbol-navigation-canvas-nodes-headings-hashtags-links-embeddings) provides the capability to jump directly to different parts of a note. But I think this request is for something different, I believe the Obsidian created blockIds end up being a set of random numbers, are you manually creating/editing blockIds across your vault? It would be helpful to hear about your workflow a bit to understand this use case better. Thanks!

**Comment by Merlin04** [comment]
yeah, I sometimes manually set blockids so that I can make links to parts of previous notes (like if I define a term). maybe there's a better way to do this? I'm still pretty new to using obsidian

**Comment by darlal** [comment]
yea, I imagine manually setting blockIds could become unmanageable as your usage grows. I think Zettelkasten crowd would say to create a separate note for the term definition. There's a lot of benefits to a separate note, as it can be embedded using the `![[note-name]]` syntax, it can have different predefined aliases to refer to it, you can just link to it using `[[note-name]]`, and you can also link using different display text `[[note-name|display text]]`, this is really the most flexible option. 

An alternative could be to make it a heading that you can refer to while keeping it in the same note, this has the benefit of being linked/embedded but without needing to micro manage blockIds.

**Comment by CoderRuq** [comment]
+1
