### ISSUE TITLE
Full-Text Search Development Plan for the Plugin

### ISSUE THREAD

**Issue by Mingzefei** [darlal/obsidian-switcher-plus#146]
Hello,

I would like to inquire if there are any plans to develop full-text search functionality for the plugin. This refers to searching not only filenames or headings but also the body of the content. Thank you.

**Comment by darlal** [comment]
Thanks for the question. I think full text search is beyond the scope of this plugin for the time being. You might take a look at [OmniSearch](https://github.com/scambier/obsidian-omnisearch), which is an existing plugin that does provide full text search in a Switcher UI.

**Comment by Mingzefei** [comment]
Thank you for your response. 
I have tried OmniSearch, but unfortunately, it does not meet my needs as it has poor support for Chinese language searches. 
Since this functionality is beyond the scope of this plugin, I will explore other methods to find a solution.
