### ISSUE TITLE
[Feature request] Option to open pdf files with external app

### ISSUE THREAD

**Issue by machado-t** [darlal/obsidian-switcher-plus#148]

**Comment by darlal** [comment]
Thanks for the suggestion. Could you elaborate a bit on the workflow you'd like to achieve in this case? I could imagine it working a few different ways. For example, I believe there is an existing Obsidian command `open in default app` which could be triggered directly from the switcher through a new hotkey, or, an option to change the existing `open` switcher behavior (hotkey) to always trigger via the default app.

**Comment by machado-t** [comment]
When opening a pdf file via Quick Switcher+, it will always open inside Obsidian. Even though I keep a lot of pdfs in my vault I prefer to open them externally. The workflow I meant could be achieved with an option that would change the default behavior of opening a pdf file via Quick Switcher to always trigger via the default app.
Thanks!

**Comment by darlal** [comment]
[Release 4.6.3](https://github.com/darlal/obsidian-switcher-plus/releases/tag/4.6.3) introduces a new command to launch files in their default app directly from the switcher in custom modes (Headings, Editor, Bookmarks, Symbol, RelatedItems). Thanks!

<img width="600" alt="image" src="https://github.com/user-attachments/assets/13a2ccf2-dbe3-423c-848f-ad3f55422c45">
