### ISSUE TITLE
[Feature request] Change the "Open in Standard Mode" ribbon icon

### ISSUE THREAD

**Issue by Anarchtism** [darlal/obsidian-switcher-plus#149]
Currently the "Open in Standard Mode" ribbon icon is the same icon that [Omnisearch](https://github.com/scambier/obsidian-omnisearch) uses. Could it be changed to the same icon the core Quick Switcher plugin uses instead?

**Comment by darlal** [comment]
Thanks for the suggestion. I believe Headings mode uses the same icon as the core switcher, but standard mode does us a different icon.

**Comment by darlal** [comment]
The icon has been updated in release [4.2.0](https://github.com/darlal/obsidian-switcher-plus/releases/tag/4.2.0). Thanks!
