### ISSUE TITLE
Feature Request: Search accented characters 

### ISSUE THREAD

**Issue by machado-t** [darlal/obsidian-switcher-plus#150]
As a user who frequently works with notes containing special characters such as accented letters (e.g., é, â, ç, ã, î), I'm finding that the current search requires exact matches, including accents. 
I propose an accent-insensitive option where inputting the basic Latin character (e.g., 'e') would return results that include both the plain character and its accented counterparts (e.g., 'é', 'ê'). Similarly, searching with an accented character should yield results that contain the plain character as well.
Thanks

**Comment by darlal** [comment]
Hey, this has come up before (see discussion #78), Switcher++ uses the builtin Obsidian searching algorithm which has this restriction. There is an open  [Obsidian feature request](https://forum.obsidian.md/t/ignore-accents-diacritics-in-search/1655/55) for this in the Obsidian forum, I would recommend commenting on that request. 

In the near term, Switcher++ will continue to use the Obsidian algorithm. As an alternative, I think the plugin [Another Quick Switcher](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher) may have this feature (I'm not entirely sure).

**Comment by machado-t** [comment]
Was this actually implemented? I don't think it's working on my end.

**Comment by darlal** [comment]
It was not, I think this should be addressed in core Obsidian. This issue should have been closed as not planned, sorry for the confusion.
