### ISSUE TITLE
[FR] Render Markdown in Search Results

### ISSUE THREAD

**Issue by julroger2013** [darlal/obsidian-switcher-plus#151]
Do you think it would be possible to render markdown in Switcher++'s results? For reasons idiosyncratic to the type of work I do (legal), a lot of my headings & callouts use italicization. It's a very modest thing - Switcher++ already functions so perfectly - but it would be nice if the italicization and any other markdown on these items rendered instead of showing the underlying markdown.

The Better Search Views plugin takes this approach with Obsidian's built-in search features, rendering callouts, italicization, highlights, etc. I'm not sure how portable that code is, nor what the restrictions are on the use of that author's code, but maybe that would provide a foundation for implementing markdown rendering in Switcher++?

Thanks for making this fantastic plugin. I use it *all. the. time** I suspect it's single Obsidian plugin that I get the most utility from.

**Comment by darlal** [comment]
I'm glad you're still enjoying the plugin! Thanks for the suggestion, I will see how feasible it is for switcher++.

**Comment by darlal** [comment]
@julroger2013 There's an experimental version of this live in [release 4.5.0](https://github.com/darlal/obsidian-switcher-plus/releases/tag/4.5.0).

When in `Headings` and `Symbol` modes, search results for Heading can be rendered similar to Obsidian's "Live Preview" mode #151. This is experimental and disabled by default, the setting `Display Headings as Live Preview` must be enabled in the plugin [General Settings](https://github.com/darlal/obsidian-switcher-plus?tab=readme-ov-file#general-settings).

With the feature turned off:

![image](https://github.com/user-attachments/assets/03b71c34-8d69-4527-8e37-12e4c0b3151c)

With the feature enabled:

![image](https://github.com/user-attachments/assets/f850cd59-3c53-4118-96bf-9b6b40215383)


Note that when the feature is enabled heading text that matches the search query will not be highlighted in the live preview result. The new "toggle preview (selected heading)" shortcut has been added to allow you to toggle between the live preview and raw text mode for the selected result.

![image](https://github.com/user-attachments/assets/7f151a1b-dace-40ae-81c1-23537f35102a)

Additionally elements (like links/tags/etc..) in the rendered html live preview are not clickable in the switcher result. It's a view only rendering.

If this works well, we may extend it to rendering of some other items in Symbol mode. Thanks!

**Comment by julroger2013** [comment]
Hello:

Sorry I never followed up on this. I was poking around a little with this feature today. The implementation with headings is very nice - I'm able to add markdown links in heading and have the display remain manageable. I like this a lot.

Would it be possible to add this rendering to all results in Symbols mode? I tend to include many callouts in my notes, and many of them contain a markdown link in the callout's title. It would be great to have just the title text of the markdown link render.

Thanks for your continued work on this plugin. It continues to be probably my most-used plugin. Bravo!

**Comment by darlal** [comment]
>Would it be possible to add this rendering to all results in Symbols mode? I tend to include many callouts in my notes, and many of them contain a markdown link in the callout's title. It would be great to have just the title text of the markdown link render.

It could definitely be added to Symbols. Callouts however are interested, because I'm not sure there would be a way to render only the title (as opposed to the entire Callout), but perhaps.
