### ISSUE TITLE
Commands mode broken since 4.1.0

### ISSUE THREAD

**Issue by Kageetai** [darlal/obsidian-switcher-plus#152]
![Screenshot 2024-04-09 at 15 33 27](https://github.com/darlal/obsidian-switcher-plus/assets/1738309/00051ae1-eeda-481c-a67c-5a422bf19869)

The command mode just displays some JS template code and doesn't work with any commands any more. When I type any commands, nothing happens and no commands are displayed, only the previous code disappears.

**Comment by Kageetai** [comment]
Oh, I see it now required the core plugin "Command Palette" to be active as well. That was not the case before, as I just had it disabled, because I didn't need it thanks to QuickSwitcher++. Guess I will have to enable it now...

**Comment by darlal** [comment]
Yes, it was updated to use the newer Obsidian APIs. The core plugin does have to be enabled - that's where the "Pinned" items comes from. Having the core plugin enabled shouldn't cause any issues, if you don't use the "Pinned" items functionality, you can just remove/reassign its default hotkey for the core plugin, and never have to deal with it 🙂

**Comment by Kageetai** [comment]
Fair enough, makes sense. Just meant to mention that this kinda requirement would be good to mention. I always try to disable any plugins I don't use, also for quicker startup time etc.
