### ISSUE TITLE
Insert in editor bug

### ISSUE THREAD

**Issue by Cloudplaygit** [darlal/obsidian-switcher-plus#154]
ctrl+i insert into editor is not working if a heading has a tag attached to it. 
It adds a # followed by the tag name instead of just the tagname.
So then using ctrl+i on a heading with a tag, the link will not work. I have to manually remove the # and then it work. 
For further clarification see the picture.  

![Screenshot 2024-05-02 192213](https://github.com/darlal/obsidian-switcher-plus/assets/146376903/4cca960b-3b76-41e3-960e-9b1b4718f2d2)

**Comment by darlal** [comment]
Thanks for the report, that indeed does look like a problem. I'll look into this.

**Comment by darlal** [comment]
This should be fixed in release [4.2.1](https://github.com/darlal/obsidian-switcher-plus/releases/tag/4.2.1). Thanks!
