### ISSUE TITLE
[Feature Request] Show one-line help text on how to enter search modes

### ISSUE THREAD

**Issue by ltroj** [darlal/obsidian-switcher-plus#155]
90% of the time I want to use quick switcher ++ in standard mode and this is where my hotkey `Ctrl + o` defaults to. It would be great if there was a short help text below the modal which says something like 

> Use `'` to search bookmarks, `#` to search headings and `@` to search symbols

That would make usage a lot easier, especially for occasional users.

**Comment by darlal** [comment]
Thanks for feature request. It's come up before, see #70 please give that one a 👍 upvote and I'll try to get it in soon. I'll close this issue as duplicate, but feel free to reopen if you feel it's different. Thanks.
