### ISSUE TITLE
Feature Request: Order Command Palette Results by Most Recently Used

### ISSUE THREAD

**Issue by friebetill** [darlal/obsidian-switcher-plus#156]
### Description

Currently, the quick switcher plugin sorts files by most/recently used, which is incredibly helpful. I would love to see this sorting feature extended to the command palette as well.

### Background

This feature request has already been discussed on the [Obsidian forums](https://forum.obsidian.md/t/order-command-palette-results-by-most-recently-used/27014). The quick switcher plugin is mentioned in the discussion, but there does not appear to be an option to enable this behavior for commands.

### Request

Please consider adding the ability to sort commands in the command palette by most/recently used, similar to the current file sorting feature. This would greatly enhance usability and efficiency.

Thank you for your consideration and for all your hard work on this plugin!

**Comment by darlal** [comment]
There are two cases when I believe Switcher++ already prioritizes recently used commands.

1. Currently when you open Switcher++ in `Command Mode` _without any search term_, it displays the list of recently use commands. First it displays the list of pinned commands, immediately following those, the list of recently used commands.
2. When you perform a search in Switcher++, the [Result priority adjustments](https://github.com/darlal/obsidian-switcher-plus/tree/master?tab=readme-ov-file#general-settings) can be used to increase/decrease the score of recently used commands (make them appear higher towards the top of the list, or, lower towards the bottom of the list).

So I believe modifying the `Result priority adjustments` setting should give you the behavior you're looking for. Please let me know if I've misunderstood something. Thanks!
