### ISSUE TITLE
Open in Editor mode produces extraneous matches... 

### ISSUE THREAD

**Issue by skirsch** [darlal/obsidian-switcher-plus#157]
See this image:
![image](https://github.com/darlal/obsidian-switcher-plus/assets/1555174/b06e82fb-af99-4416-aa09-0b79a9b78035)
The text "oracle" doesn't appear in several of these "matches" (like Create Bootable and the Cloudberry one).

And it ALWAYS shows the current tab name and "Backlinks for _current tab name_" In this case, I was on "Create Bootable ISO ..."

This seems to be a bug and it's repeatable.

Also, I'd like the search to ONLY match the text in the title of the open tab. I have zillions of tabs open and I'd like to switch with the search matching just the TITLES. 

I'm happy to make a generous donation if you can fix these two things. 

Also, happy to do interactive debugging to get to the root of the problem.

FANTASTIC work.... super impressive.

**Comment by darlal** [comment]
Hi there, glad you're finding the plugin useful. There are a few things happening here, so I'll try to call them out separately.

>it ALWAYS shows the current tab name and "Backlinks for current tab name"

This is a feature of Switcher++ and is configurable. Editor mode enables you to switch between active editors and "Side panel" views ("Backlinks for current tab name" is a Side panel view). See [Include side panel views](https://github.com/darlal/obsidian-switcher-plus?tab=readme-ov-file#editor-navigation-configuration) setting documentation for details.

>I'd like the search to ONLY match the text in the title of the open tab

The "Title" of a tab could be several different things, 1) the filename without path 2) the first H1 heading 3) some Obsidian generated text (usually also containing filename). The setting [Preferred suggestion title source](https://github.com/darlal/obsidian-switcher-plus?tab=readme-ov-file#general-settings) allows you to configure which one is prioritized when searching. Here's the important bit, if a match is not found in the preferred title source, it falls back to searching the whole filepath. When there's a match in the fallback search, it is scored much lower than the preferred source match would be.

>The text "oracle" doesn't appear in several of these "matches" (like Create Bootable and the Cloudberry one)

Switcher++ uses the Obsidian builtin fuzzy search feature. Fuzzy search allows there to be partial matches for the word you're looking for (so in this case, you might get non-sequential matches for the word "oracle"). 

For the results where the word "oracle" does not appear in the "Title", take a closer look at the filepath for those results, you'll see that there is a fuzzy match in the filepath. What's happening is that there was no match in the title, which causes it to fallback to searching the filepath, and fuzzy matching there (you can see the matched text is highlighted differently).
![search](https://github.com/darlal/obsidian-switcher-plus/assets/5191776/7e517a21-32cf-49b9-ba6e-a3b9dd153759)

Hopefully this sheds some light on the behavior you are seeing. Thanks!

**Comment by skirsch** [comment]
well I see that now, but it's super confusing for those who are relative newbies to Obsidian. 

I can think of 2 solutions to avoid future bug reports.

1. don't use the fuzzy match... it's not needed for these cases
2. Put the fuzzier matches in a section at the bottom

I'd prefer #1.

thanks for writing this plugin it's amazing.

**Comment by darlal** [comment]
Thanks for the feedback. There's no plan to change the search algorithm for the time being, but if that changes will take this under consideration. Thanks again!
