### ISSUE TITLE
Doesn't see *.txt files added by UNITADE.md plugin

### ISSUE THREAD

**Issue by d9k** [darlal/obsidian-switcher-plus#158]
See https://github.com/Falcion/UNITADE.md/issues/67

Was working with [deathau/txt-as-md-obsidian](https://github.com/deathau/txt-as-md-obsidian) plugin before Obsidian upgrade (`1.3.5 -> 1.6.3`) perfectly

If I rename one of *.txt files to *.md Obsidian Switcher sees it immediately.

Version `4.2.2`

**Comment by d9k** [comment]
Tested `3.3.9`, same problem

**Comment by d9k** [comment]
Turns out Obsidian Switcher++ sees *.txt files if I enable **core** Quick Switcher plugin. But why?

**Comment by darlal** [comment]
Switcher++ extends the core Quick Switcher, so it's expected that the core switcher remains enabled. The core switcher provides some settings for managing "attachments" and "external files" (non-md files). I think what might be happening in this case is that with the core switcher disabled, those settings are maybe unspecified or disabled - which is equivalent to "off", so your .txt files are not be searched at all.
