### ISSUE TITLE
[Feature Request] Quick Swicher++ Open in Editor Mode for SIDEBAR Notes

### ISSUE THREAD

**Issue by FelipeRearden** [darlal/obsidian-switcher-plus#16]
Hello @darlal  !!!

I recently find out about QuickSwicther++ and I don't know how I could operate before without it. Thank you so much for creating this to our community!

My feature request is related to notes placed in the Sidebars (right and Left).
- If you browse in Discord for the past month you will see a lot of people placing Notes in the Sidebar as a quick alias when reading or writing.  

My workflow is this: 
- I have a bunch of source notes splited in the Panes and [Tabs](https://github.com/gitobsidiantutorial/obsidian-tabs);
- I have my "Quicknote" note in `EDIT MODE` (which is a [Workbench Note](https://github.com/ryanjamurphy/workbench-obsidian)) on the Right Sidebar
- As far as a I read call the Sidebar trough a hotkey and start taking some notes
- Then I hide the Sidebar to continue to reading.

![Screen Shot 2021-06-22 at 10 30 47](https://user-images.githubusercontent.com/85180696/122934167-ab97f980-d345-11eb-8351-781f6c35c6f9.png)

![Screen Shot 2021-06-22 at 10 31 16](https://user-images.githubusercontent.com/85180696/122934182-afc41700-d345-11eb-9527-1b03610470b3.png)

### My Feature Request: 
Adding to the feature `Quick Switcher++ Open in Editor Mode` list notes that are placed in the Sidebar (right and left). 

![Screen Shot 2021-06-22 at 10 39 28](https://user-images.githubusercontent.com/85180696/122935060-6a541980-d346-11eb-9308-b589cc694a3f.png)
As you can see my Quicknote is not in the list

This way I can navigate between the notes only using my keyboard.

I hope you like my suggestion. Let me know if you need any additional information!
Thanks for your time!

**Comment by darlal** [comment]
Hey @FelipeRearden! Glad you find it useful 😃

Thanks for the detailed post. If I understand correctly, you want to be able to switch to a note that is open in one of the sidebars. And presumably, if that sidebar is collapsed, you want it opened with the note focused. Also, you're not wanting to see all the "panels" that live in the sidebars, like search/links/etc.. Is that right?

Sidebar editors are currently being excluded, but I think they can be added to the editor list as well.

**Comment by FelipeRearden** [comment]
Hello @darlal !

Fist of all, thanks for reading my post and for your reply.

Makes me very happy to know that my detailed post helps. I always try to explain the usage for the feature that I am suggesting. 

You are 100% right: it's basic to include notes placed in the sidebars in the list of notes available in the `Quick Switcher++ Open in Editor Mode`:
- Yes only notes, not plug-ins as "Search", "Backlinks", "Outline" ....
- Yes, if the sidebar is collapsed , it will open with the notes focused 

Would be amazing if you could include the sidebar notes in the list: a game changer for my workflow!

Thanks and have a great day!

**Comment by darlal** [comment]
@FelipeRearden this feature has been implemented in the [0.13 release](https://github.com/darlal/obsidian-switcher-plus/releases/tag/0.0.13). There is now a setting to allow you to configure which view types from the sidebar/panels will show up in the switcher. I will close this issue out.

**Comment by FelipeRearden** [comment]
Hello @darlal !

Thank you so much for this feature !!!! 

### Just one information for you:

I just try to  update QuickSwitcher++ to try the new feature (0.0.10 >>> 0.0.13) and it didn't update.

Take a look, the information is that the update was successful, but I still remains in 0.0.10
![Screen Shot 2021-07-02 at 08 09 42](https://user-images.githubusercontent.com/85180696/124266562-85c0e080-db0d-11eb-9e34-44191e561242.png)

![Screen Shot 2021-07-02 at 08 10 44](https://user-images.githubusercontent.com/85180696/124266581-8bb6c180-db0d-11eb-91b9-0a6c0dc52a3b.png)

Before I write this comment I try to uninstall and install QuickSwitcher++ again from the zero  but I got the same result. 
Close and Open Obsidian had zero effect to :( 

Let's see if our friends from our community can install 0.0.13 to see if is something that only happens to me. 

Have a great day!

**Comment by FelipeRearden** [comment]
Hello @darlal !

Sorry for the late reply. I’m on mobile right now

First of all, thank you so much for your detailed and rich reply. 

I use a CSS snippet to “hide” the `tiltebar` itens with the same color.

I’m 100% sure that I’m not on 0.12.9. I’m almost sure that I’m on 0.12.3 or 0.12.4 or 0.12.5. 

I get home in about 2 hours:
- I’m gonna confirm my version;
- I’m gonna check the plugin directory;

thanks for you help. I reply to you soon  and we close this!!!

**Comment by FelipeRearden** [comment]
Hello @darlal !!!

1. My Obsidian version is 0.12.3 (I let the automatic update disable)
2. This is my `manifest.json` file:
![Screen Shot 2021-07-02 at 15 39 30](https://user-images.githubusercontent.com/85180696/124316618-42399700-db4c-11eb-94cc-13d1a3785694.png)

If the 0.0.13 version is ready for 0.12.9 it's okay :) I wait until the next Obsidian release without any problem!

I don't wanna bring you more problems to you and I am happy to know that everything is okay with the update for the 0.12.9 users.

Thanks again!

**Comment by darlal** [comment]
@FelipeRearden Ah I see. yea, 0.13 requires Obsidian 12.9 at a minimum. This is because of some core API breaking changes that were introduced. I hope the 12.9 will be made public really soon.

It's still weird that Obsidian was offering you the upgrade at all though, but perhaps there was some bug with the auto update process in back in 12.3.

I think you have the right Obsidian/plugin version combo for now. The new feature will be there once you upgrade 😄

**Comment by FelipeRearden** [comment]
@darlal ! 

It is just a matter of time now :)

As soon as 0.12.09 is released I post a comment here to let you now that I test the 0.13 version.

Again, sorry for the unnecessary bothering! 

I wish you a fantastic weekend and thanks again for making this feature!
Thanks!

**Comment by FelipeRearden** [comment]
Hello @darlal !!!!

Just to inform you that the new feature sidebar feature works absolutely fantastic in 0.12.10 ! 

Thank you so much for doing this. I'm extremely grateful to you. :)

[off-topic] Do you use Obsidian Discord? I wanna DM you about something unrelated to QuickSwitcher.

**Comment by darlal** [comment]
@FelipeRearden glad to hear it. Yes, I'm on the discord, I'm just pinged you.
