### ISSUE TITLE
In vault mode show vault name instead of the full path

### ISSUE THREAD

**Issue by anareaty** [darlal/obsidian-switcher-plus#160]
Right now the full path to the vault is shown on the first line and on the second line. It make sense to only leave it on the second line, and on the first only show vault name.

 
![Снимок](https://github.com/darlal/obsidian-switcher-plus/assets/55949830/aba53fb2-44a6-441d-8266-7f26c6619e24)

**Comment by darlal** [comment]
It should be only showing the vault name on the first line. Looks like the vault paths aren't being normalized on your platform and causing some problems with Windows paths. Thanks for the report.

**Comment by darlal** [comment]
This should be fixed in [release 4.4.0](https://github.com/darlal/obsidian-switcher-plus/releases/tag/4.4.0). Thanks!
