### ISSUE TITLE
Prompt words in Quick Switcher++ windows gone after OB upgraded to 1.6.5

### ISSUE THREAD

**Issue by Snowboy801** [darlal/obsidian-switcher-plus#163]
Hi! Darlal,

Thank you for your smart Quick Switcher++ ! It improves my work efficiency a lot. 
I have even been preparing a course to promote this handy plugin. But now it got stunk. 
——Operation prompt words in QS++ windows at the bottom, such as "ctrl \ open the right", "ctrl i insert in editor" are gone in all modes where filter function applicable.

Normal operation prompt words:
![240626_1209_291214](https://github.com/darlal/obsidian-switcher-plus/assets/173869104/c3966525-017c-460c-be4a-57142b8fe387)

Error example (only shows filter prompt words but no operation prompt words):
![240626_1214_301215](https://github.com/darlal/obsidian-switcher-plus/assets/173869104/e9965460-c11d-4417-ae31-7daaeaa43600)

All these open/insert operation function themselves work well. The problem is the prompt words disappeared. It is hard for beginner to learn, to use the plugin.

The problem happens only when Filter options exit. 
QS++ works well before I update Obsidian to 1.6.5. But OB 1.5.12 is OK. So I think it is a match problem.

Please help to check and fix. Thanks!

**Comment by Snowboy801** [comment]
After uninstall 1.6.5 and tried:
OB 1.6.3 is NG.  I did not test other 1.6.x.  
OB 1.5.12 is OK.
fyi

**Comment by darlal** [comment]
I'm sorry the plugin seems to be misbehaving. Obsidian 1.6.1 introduced some changes that caused a similar problem to the one you seem to be running into. QS++ [version 4.2.2](https://github.com/darlal/obsidian-switcher-plus/releases/tag/4.2.2) should have fixed that problem. You might just need to upgrade QS++ to the most recent version. Please check to see what version of QS++ you have installed and report back. Thanks!

**Comment by Snowboy801** [comment]
Thanks for your prompt reply! Indeed, QS++ 4.2.2 work well in OB 1.6.5.  (What I installed before was QS++ 4.2.1. )
I should check your releases notes carefully. Now I understand the meaning "Fix to make custom prompt instruction visible".   :) 
Have a nice day!
