### ISSUE TITLE
Are the hotkeys while in the quick switcher documented anywhere?

### ISSUE THREAD

**Issue by Anarchtism** [darlal/obsidian-switcher-plus#164]
So far I found
Ctrl + J = Down
Ctrl + K = Up

Ctrl + P = Up
Ctrl + N = Down

Ctrl + I = Insert highlighted note as link in current file
Ctrl + O = Open in new window (desktop only)

**Comment by darlal** [comment]
The hotkeys are generally displayed in the "Prompt Instructions" section at the bottom of the switcher, for the modes in which they are active. Like this:

<img width="698" alt="image" src="https://github.com/darlal/obsidian-switcher-plus/assets/5191776/c3c4e39d-d8b7-4ef1-aa80-6e559240fda3">

The only exceptions are the [Navigation keys](https://github.com/darlal/obsidian-switcher-plus/blob/master/src/settings/switcherPlusSettings.ts#L116) which you've already found 🙂 and the [Close when empty keys](https://github.com/darlal/obsidian-switcher-plus/blob/master/src/settings/switcherPlusSettings.ts#L127) but that one is configurable in the plugin settings. Thanks!

**Comment by Anarchtism** [comment]
Ah, I didn't see the prompt instructions much because I mainly use mobile.

Maybe it would be good to add the navigation keys to the readme.
