### ISSUE TITLE
Question: How to show only exact matches

### ISSUE THREAD

**Issue by merlinuwe** [darlal/obsidian-switcher-plus#167]
Thanks for your great plugin.

When I search for a word, I want to see only search results with this word.

Example: I'm searching for the word "Geschenk"

![image](https://github.com/user-attachments/assets/3ac65644-c447-4b78-a001-009652cebc16)

Is there a way to show only the matching results and not the ones framed (and below)?

**Comment by darlal** [comment]
Glad you're finding the plugin useful 🙂 

> When I search for a word, I want to see only search results with this word.

Switcher++ uses the Obsidian builtin fuzzy search algorithm. Fuzzy search allows there to be partial matches for the word you're looking for (so in this case, you might get non-sequential matches for the word "Geschenk"). This likely won't change in the near term. "Full" matches when they are found should score much higher than these partial matches and rise to the top of the list, as is visible in your screenshot. There's also the [another-quick-switcher](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher) plugin, which might offer some different search mechanics.
