### ISSUE TITLE
Command list just doesn't work

### ISSUE THREAD

**Issue by deafmute1** [darlal/obsidian-switcher-plus#173]
Have default settings, when using the command mode prefix it does nothing, it just searches the vault for ">". No commands are surfaced.

**Comment by darlal** [comment]
It's likely you have the Obsidian core "Command palette" plugin disabled, that core plugin needs to be enabled as well. The documentation will be updated to make that more clear. Thanks!

**Comment by darlal** [comment]
Please feel free to reopen this issue, if that doesn't address it. Thanks!

**Comment by Mistmage** [comment]
It seems that i have the same problem, unless i use a hotkey to summon a certain mode, typing any command activator just searches for it in the vault.
I definitely have "Command palette" enabled, and the default settings.

The most baffling thing, is that it is like that in a literal newly created vault with only Quick Switcher++ on.

**Comment by darlal** [comment]
>unless i use a hotkey to summon a certain mode directly, typing any command activator in a vanilla quick switcher just searches for it in the vault.

@Mistmage I think you're referring to default Obsidian builtin switcher when you say the "vanilla quick switcher"? After installing Switcher++ you should transfer the hotkey that launches the vanilla quick switcher to instead launch Switcher++. In other words, change the hotkey that triggers the vanilla switcher (its global command is `Quick switcher: Open quick switcher`) to instead trigger Switcher++ (its global command is `Quick Switcher++: Open in Headings Mode`). The Switcher++ features cannot be used from the vanilla switcher.

**Comment by Mistmage** [comment]
Ah, i see, i was confused because there was no "Generic" option among all the commands. thanks for explaining!
