### ISSUE TITLE
[BUG] Bookmark search returns files that were deleted

### ISSUE THREAD

**Issue by deafmute1** [darlal/obsidian-switcher-plus#174]
Bookmark search returns files that were deleted.
In the bookmark pane, these are automatically removed. Therefore, bookmark search in quick switcher deviates from the bookmark pane.

Workaround: Recreate file, remove it from bookmarks, delete it again.

**Comment by darlal** [comment]
Thanks for the report!

**Comment by darlal** [comment]
This should be fixed in [release 4.5.1](https://github.com/darlal/obsidian-switcher-plus/releases/tag/4.5.1). Bookmarks are no longer displayed for files that were deleted. Thanks!
