### ISSUE TITLE
Incompatible with Obsidian v1.7.2

### ISSUE THREAD

**Issue by liamcain** [darlal/obsidian-switcher-plus#177]
Hi! We just made some API changes in Obsidian 1.7.2 and this plugin was impacted. We removed `PreparedQuery` and `fuzzySearch` in favor of the newer API `prepareFuzzySearch`.

There are some more details about the change [here](<https://github.com/obsidianmd/obsidian-api/blob/master/CHANGELOG.md#housekeeping>).

---

If I have time later today, I'll try to submit a pull request with the needed fixes. Sorry for the disruption!

**Comment by darlal** [comment]
Hey @liamcain! It's been a long time 🙂 Thanks for the head's up.

I guess I didn't realize that those functions had been deprecated. I imagine that change will cause a lot of test failures, PRs welcomed! I likely won't have any cycles to devote to it until the weekend at the earliest, so if you don't get to it, I'll pull one together over the weekend. Thanks!

**Comment by liamcain** [comment]
Okay, I just checked and while we removed `fuzzySearch` and `prepareFuzzySearch` from the API spec, they are still exported from Obsidian, so thankfully nothing is broken currently. I took at stab at trying to refactor the plugin but PreparedQuery gets passed around a lot more than I expected 😅.

Not to mention all those pesky unit tests lol

**Comment by darlal** [comment]
Ok, thanks for the update. Yea, those functions are pretty pervasive, I'm starting the upgrade now. Thanks!

**Comment by darlal** [comment]
@liamcain the update is completed and available in [release 4.6.0](https://github.com/darlal/obsidian-switcher-plus/releases/tag/4.6.0). Thanks for the heads up! 🙂

**Comment by liamcain** [comment]
<img width="370" alt="image" src="https://github.com/user-attachments/assets/ea173da2-7ec3-446d-9159-f3ac487b4cc2">

Ouch! Sorry this ended up being such a chore 😧

I was really expecting the damage to be minimal, but I guess that's to be expected for a plugin built around fuzzy searching.

**Comment by darlal** [comment]
Yea, it actually wasn't that bad. There's one or two usage patterns that's replicated in a bunch of places, and the associated tests. The actual change itself was pretty straightforward just repetitive. 

Glad to be on the newer api, in the future I'm thinking of adding a setting to enable users with larger vaults to switch to the faster simple search API.
