### ISSUE TITLE
[FR] Specify the type of symbols to search for in the Symbol Navigation 

### ISSUE THREAD

**Issue by husterw** [darlal/obsidian-switcher-plus#185]
When I try to locate a specific link using the symbol mode, the search results show other symbols with the same name. While I can adjust the plugin settings to show only links, when I want to locate a heading next time, I have to go back to the settings to reopen `Show Headings`, which is very cumbersome.

It would be great to allow users to filter symbols by type during the search. This feature could be implemented using additional trigger characters, such as `@` for no filtering, `@!` for showing only links, and `@#` for showing only headings, etc.

**Comment by darlal** [comment]
This kind of filtering can already be done using the [Quick Filters feature](https://github.com/darlal/obsidian-switcher-plus?tab=readme-ov-file#quick-filters). You can narrow down the type of Symbol you want to search through using Quick Filters, which was introduced in [release 3.1.0](https://github.com/darlal/obsidian-switcher-plus/releases/tag/3.1.0). Thanks!
