### ISSUE TITLE
Searching by heading with # doesn't work in Standard Mode

### ISSUE THREAD

**Issue by alexzadeh** [darlal/obsidian-switcher-plus#186]
Version 4.6.2

I'm experiencing an issue with Quick Switcher++ in Standard Mode. When I open it using CMD-O and type #, the switcher immediately closes, and a document opens with the heading focused.

Interestingly, if I change the Headings list mode trigger to 'h', it works fine, and I'm able to search for headings. This suggests there's something unusual happening with the hash character.

Thanks for looking into this.

**Comment by darlal** [comment]
Sorry you're running into trouble. That does sound odd. A few things to try:

1. Are there any errors being reported in the developer console? You can open the console from the menu View->Toggle Developer Tools.
2. You can launch Switcher++ directly into Headings modes using the [global command](https://github.com/darlal/obsidian-switcher-plus?tab=readme-ov-file#global-commands-for-hotkeys) `Quick Switcher++: Open in Headings Mode`. Keeping `#` as the trigger character, If you bind that global command to a hotkey and launch that way, does that work?
3. Try the Obsidian out of the box switcher. Run the global command `Quick switcher: open quick switcher` (note: this is the built in Obsidian switcher, not Switcher++), type the `#` character, what happens?
4. Do you have any automation scripts or processes that trigger some action? It could also be another Obsidian plugin interacting in a weird way. Please try disabling other plugins and see if the behavior is still reproducible.

> and a document opens with the heading focused.

Does the same document always get opened, or, is it a different one each time?

**Comment by alexzadeh** [comment]
Thanks for your reply and sorry for my delay in getting back to you. 

1. No errors are being reported
2. It opens fine, showing # and lists headings. However, if I delete # and then add it back I get the same problem as before.
3. No problems with the built-in Obsidian switcher. 
4. I've tried disabling all the other plugins and it doesn't make a difference.

It's not always the same document, but it's always a recent document.

It's really strange! But thankfully, not a big deal to workaround. Switcher++ is fantastic. 

Thanks
