### ISSUE TITLE
unable to invoke the command bar anymore

### ISSUE THREAD

**Issue by lethefrost** [darlal/obsidian-switcher-plus#19]
I am not sure what went wrong. This plugin used to work really well (and thank you!!❤️) but today I just found it doesn't work anymore. I tried to restart Obsidian, restart the system, turn off and on this plugin and re-assign hotkeys to the commands. None of them helped.

I noticed that the recent official release had changes to the quick switcher in the new version, could this be the reason for it? I now have Obsidian v0.12.7. 

Thanks a lot for this plugin!

**Comment by FelipeRearden** [comment]
@lethefrost 

Take a look at this post: https://github.com/darlal/obsidian-switcher-plus/discussions/18

**Comment by darlal** [comment]
Thanks @FelipeRearden. @lethefrost 12.7 changes broke the plugin. As soon as core is updated with the changes I need, I'll get this fixed.

**Comment by FelipeRearden** [comment]
Everything is gonna be okay again 🙏  !!!

**Comment by lethefrost** [comment]
> @lethefrost
> 
> Take a look at this post: #18



> Thanks @FelipeRearden. @lethefrost 12.7 changes broke the plugin. As soon as core is updated with the changes I need, I'll get this fixed.

Thank you two! 🙏

**Comment by darlal** [comment]
And we're live with 12.9 [compatibility](https://github.com/darlal/obsidian-switcher-plus/releases/tag/0.0.13). I will close this issue out.
