### ISSUE TITLE
[Feature Request] `New List Mode`: Active Folder List

### ISSUE THREAD

**Issue by FelipeRearden** [darlal/obsidian-switcher-plus#25]
Hello  @darlal !!!

I have an idea for a new list type: A list that only shows the notes from the folder where the active note is located.
- The `Active Note` will not be in this list
- Any `open Note` from the same folder will not be in this list

## Idea

**1- Image a Folder with these structure:**

Folder1
--> NoteA
--> NoteB
--> NoteC
--> NoteD
--> ImageA (.png)

**2- On Obsidian, we have these two notes in the screen (open)**
--> NoteA is open 
--> NoteB is open and is the `Active Note`

**3- When calling `Quick Switcher++: Open in Active Folder Mode` the following notes will be showed (only notes from the Folder1 that were not Open):**
--> NoteC
--> NoteD
--> ImageA

**4- Hitting `Enter` Open the Note and Hitting `Cmd+Enter` open the Note in a new Tab**
- Maybe a setting just like `Open Symbol in new Pane` to define the default behavior.

## Why I'm requesting this ?

When I'm working on a specific project I prefer to create a specific folder and start generating notes from this project inside that folder. 

Having a QuickSwitcher List Mode that only shows sources from this project would save me a lot of time since I love to work with keyboard hotkeys 

Thanks for reading this. Let me know if you need more information. 

I wish you a fantastic day!

**Comment by darlal** [comment]
Hey @FelipeRearden thanks for the suggestion. I wonder how general that applies though, I will give this some thought. 

Have you seen the [ quick-explorer plugin](https://github.com/pjeby/quick-explorer)? it enables quick browsing of the vault (or just the current folder) and is keyboard friendly. It might get you pretty close to what you're looking for.

**Comment by FelipeRearden** [comment]
Hello @darlal !!!

Thanks for your reply and he suggestion about Quick Explorer ! I use Quick Explorer and I like a lot :)
- With QuickSwitcher++ and Quick Explorer I don't have to use the File Explorer Anymore 🙏 

The dealbreaker for me in this `New List` is the ability to just select the notes that are not open in the folder.
- Quick Explorer shows all notes from a folder.  

My idea: 
-> Workspaces list to select the right workspace for the workflow;
-> Edit List for navigate in the Open Notes
-> Symbol List for navigate int the Headings in the Active Note
-> `New List` for select notes that are closed in the active note folder :)

I will be happy whatever you decide @darlal ! but I think could be a good addition to our `Lists`

Have a great day and thanks for everything :)

**Comment by darlal** [comment]
@FelipeRearden this feature is live in [release 1.0.9](https://github.com/darlal/obsidian-switcher-plus/releases/tag/1.0.9). Happy note-taking!

**Comment by FelipeRearden** [comment]
> @FelipeRearden this feature is live in [release 1.0.9](https://github.com/darlal/obsidian-switcher-plus/releases/tag/1.0.9). Happy note-taking!

Thank you very much @darlal !!!!!!! 

Working perfect on version `1.0.9` Obsidian `0.14.6`

I just say that I'm really happy to have this new feature :)

Thank you very much @darlal for making my Obsidian dreams came true 🌞 . This is a feature that I really really need !!!!!

You are an Obsidian legend 🥇 !!!!!

**Comment by darlal** [comment]
@FelipeRearden one minor update, I exposed a setting to exclude files that are already open from the list. This is live in release [1.0.10](https://github.com/darlal/obsidian-switcher-plus/releases/tag/1.0.10). Thanks!

**Comment by FelipeRearden** [comment]
Hello @darlal !!!!

Sorry for my late reply :)

> @FelipeRearden one minor update, I exposed a setting to exclude files that are already open from the list. This is live in release [1.0.10](https://github.com/darlal/obsidian-switcher-plus/releases/tag/1.0.10). Thanks!

The settings checkbox is an spectacular idea !!!!!!! This way every user has a way to work :)

### Feedback from Version `1.0.10`

**Just to see if we are on the same page…**

> Enabled: related files which are already open in an editor will not be displayed in the list. 
> Disabled: All related files will be displayed in the list.

From my tests on Obsidian 0.14.6, the Exclude open files ALWAYS NOT display files that are already open even when the checkbox is Disabled

In other words ….

Folder 1
-> Note A
-> Note B (Active Note)

Related Items Setting:
- Disable -> checkbox is off

Related Item Behavior
-> Note A

Related Item Expected Behavior when Disabled
-> Note A
-> Note B (Active Note)

---

Working perfect when Related Items Setting = Enabled ✅

Before write this feedback I restart Obsidian and did the test again to confirm the behavior.

Maybe is something on my end but as always I share anything that I saw on QS++ with you  :)

---

Let me know if need any information ! 

Have a great day!!!!!

**Comment by darlal** [comment]
The "source" file is never displayed in the list. That is, the file for which the related items command was triggered is never displayed in the list.

So in your example, `Note B` is the active source file. You want to see the other files related to it, so `Note B` itself is not in the list.

To expand on your example a bit, let's say you also had `Note C` in that same folder. `Note B` is open _and_ active, `Note A` is also open, but _not_ active. With `Exclude open files` enabled, the list would only show `Note C`, because B is the source active file, and A is already open.

**Comment by FelipeRearden** [comment]
Hello @darlal !!!!

You are 1000% right !!! 

Forgive me for my poor feedback :) 

Now it's crystal clear for me the concept for **Related Items** and the behavior of the checkbox 
- it's a clever way to define what will be present in the modal :)

Sorry for the mistake :) 

Thanks for you reply and have a great day !!!!

**Comment by darlal** [comment]
Your feedback was great, I just wanted to describe in detail the way that it works. I have much bigger plans for related items 😄 so I wanted to get the paradigm right.

**Comment by FelipeRearden** [comment]
> Your feedback was great, I just wanted to describe in detail the way that it works. 

💙 💙 💙

> I have much bigger plans for related items 😄 so I wanted to get the paradigm right.

Wooooowww I cant wait to see what you planning for the future. i know that will be amazing 👀 👀 👀 👀 👀 👀 👀 👀
