### ISSUE TITLE
[Feature request] Add quick switch for vaults

### ISSUE THREAD

**Issue by sambody** [darlal/obsidian-switcher-plus#26]
I request an additional functionality: to quickly open (or switch to) a different vault. 
Right now, there is a core command (and shortcut possible) to open de vault modal window, but I still need to use the mouse to select the other vault.

One idea: a command `Quick Switcher++: Open in Vaults Mode` - then selecting the vault with arrows/enter.

Another idea: define a specific command to open a specific vault. Defined in preferences.

Thanks,

**Comment by darlal** [comment]
Thanks for the ideas. I'm not sure that the necessary APIs are exposed to make this work reliably. I will take a look.

**Comment by guntern** [comment]
I also really like the idea of a smooth quick switching between vaults. I would suggest something like the Ctrl+R method of VS Code to switch workspaces there. Beside having the possibility to select the other vault with up and down, one could start typing the name of the vault to be opened. This way the hands could stay at the keyboard ready for further writing.

**Comment by Neilabh21** [comment]
I would like to add my support towards this request, I like to keep different things in different vaults, and it would be useful to have a way to switch between vaults. That way, I won't have to keep multiple instances of Obsidian open at the same time.

**Comment by darlal** [comment]
[Release 4.0.0](https://github.com/darlal/obsidian-switcher-plus/releases/tag/4.0.0) adds (experimental) support for opening existing vaults on Desktop platforms.
