### ISSUE TITLE
Switch with full text search

### ISSUE THREAD

**Issue by nicolasmarc1** [darlal/obsidian-switcher-plus#27]
Hello!

I just wanted to know if it was possible to have full text search in open switcher++, basically just having the existing search future in the same kind of palette that your plugin to be able to navigate the results up and down with the keyboard (unlike the current obsidian search in the sidebar) like for instance in Notion or other similar apps.

Thanks a lot!

**Comment by darlal** [comment]
I believe there is a another plugin which enables content search in a similar way to what you describe. I don't have it installed, but I believe it's this one [Obsidian Ripgrep](https://github.com/dustinknopoff/obsidian-rg). Worth checking it out.
