### ISSUE TITLE
[Feature Request] Symbol List Mode -> A New Toggle for Block References Links

### ISSUE THREAD

**Issue by FelipeRearden** [darlal/obsidian-switcher-plus#28]
Hello again @darlal !!!!

This Feature Request is related to the content of the toggle `LINKS` in the Symbol List Mode. 

In Obsidian we have three types of  internal LINKS:
- Internal Links: `[[MyFileName]]`
- Embed Links: `![[MyFileName]]` 
- Block Reference Links: `[[MyFileName#^abc1234]]`

In QuickSwitcher++ we have two toggles to show these links in the List View:

![Screen Shot 2021-10-06 at 06 22 39](https://user-images.githubusercontent.com/85180696/136179825-d131a544-3c9f-4054-98c0-ce86c44306b2.png)

Links:
- Internal Links: `[[MyFileName]]`
- Block Reference Links: `[[MyFileName#^abc1234]]`

Embed:
- Embed Links: `![[MyFileName]]`

### My FR
My FR is a new toggle to separate **Internal Links** and **Block Reference**. This way we will have these toggles:
- Heading
- Tags
- Links >>> `([[MyFileName]])`
- Embeds
- Block References >>> `([[MyFileName#^abc1234]])`

My suspicion is that Obsidian has a way to identify/separate blockreferences and links! 

Looking at the Outgoing Pane we can see that a theme can define different icons to these two types of links:

![Screen Shot 2021-10-06 at 06 28 10](https://user-images.githubusercontent.com/85180696/136180109-d639381b-85cb-4eed-8757-32b81675e289.png)

### Why I'm Requesting this

Since I'm a keyboard lover I use the Symbol Mode as an Outline Core Plug-in to Navigate between Headings in the current note. Since I use headers to organize my notes, it's much better to use the Symbol List Mode :)

My book notes has a lot of block references (300 for each book note). Since English is not my native language I need to use block references to connect what I'm writing (or translating) about a book (permanent notes) with the original source (literature note or books highlights notes) that are in English.
- If something felt wrong in the future, I have the original source to study again and make corrections. 

![Screen Shot 2021-10-06 at 06 35 20](https://user-images.githubusercontent.com/85180696/136180277-96f320d2-a4ed-47a6-b58e-71773b0251b9.png)

I use links (backlinks) as everybody uses: create new content that needs reference for crossing content inside the vault: 
- Person of Interest: [[Richard Feynman]],  [[James Clear]] ...
- Topics: [[Journaling]] [[Morning Routine]] ...

When I have Toggle Links and Headings, My Symbol List Mode has a lot of block references that don't help me: I have a hard time to find the [[links]] inside the note from each header :(

![Screen Shot 2021-10-06 at 06 39 10](https://user-images.githubusercontent.com/85180696/136180332-7bad4fd2-32ee-4a57-b20f-86055093b7b8.png)

That's why I'm requesting a new toggle -> to only toggle Links and Headings :)

--- 

I hope you like my suggestion and thanks for reading this :)

I wish you a fantastic day!!!!

**Comment by darlal** [comment]
@FelipeRearden are these block reference links pointing to different locations in the same files that contains the link? In other words, are the links "internal" to the same md document? for example `foo.md` contains links to `foo.md#^block_ref` If that's the case then a more general approach could be an option to hide "self-referencing" links.

If they're not self-referencing links, then I wonder how generally this applies beyond your personal workflow. In this instance of your workflow, you want to hide block links because they point to booknotes. But what about block links that point to non-booknote blocks? those would all get hidden too, so you wouldn't see them in other aspects of working with the vault where you might want to see them. Or, what about links that point to headers e.g. `bar.md#baz_header` would you want to be able to hide those too?

I'm asking to try and understand your use-case **and** to try and figure out if/how such a feature could be more generally applicable to the wider user base :)

**Comment by FelipeRearden** [comment]
Hello @darlal !

Thank you so much for taking a time to answer me :)

> In other words, are the links "internal" to the same md document? for example foo.md contains links to foo.md#^block_ref If that's the case then a more general approach could be an option to hide "self-referencing" links.

No, my internal links are pointing to a different note. 

Following your example, my note `foo.md` have links to a note  `bar.md` in the format `bar.md#^blockref`  

> But what about block links that point to non-booknote blocks? those would all get hidden too, so you wouldn't see them in other aspects of working with the vault where you might want to see them.

Yes! that's why:

In my opinion that is the role of the block links. They used as pins the map for reading the content of the note. I'm reading this and I know that here there is an additional content that I need to be aware.  

For a search or a "walk" inside the note content with the Symbol list, the `[[bar.md]]` is used to show the destination. 

I'm my case, I have in my `foo.md` note:
- a bunch of block links `bar.md#^blockref`to know where in to look when reading;
- a link to the `bar.md` note in the format `[[bar.md]]` to use as a unique reference or few times in the text when I need to reference to the whole content and not a point in the content.

> Or, what about links that point to headers e.g. bar.md#baz_header would you want to be able to hide those too?

I have to be honest with you I don't use `bar.md#baz_header` and this is a point that I have to agree with you: that would be better to not hide these sub-types of block link. 

Is it possible to differentiate block links and block headers and treat block headers as links?  If not, I think the only option is hiding. 

---

In my humble opinion central point of my FR is to add a new toggle without  breaking any present workflow and bring a new opportunity to the user adjust your workflow:
- if the user need all links, toggle `Show Links` and `Show Block Links`and `Show Embeds`
- if the user need only [[links]], toggle `Show Links`   
- if the user need only Headings and tags, toggle `Show Headings` and `Show Tags`

It's very common in Obsidian that new features from Obsidian triggers new workflows that the user didn't thought about or that wasn't possible in the past.
- I'm always talking, watching and looking to our community to understand new features to  see what I can do with it :)
- Today I learn about`bar.md#baz_header` and I'm gonna spend many days thinking about how to bring this to my workflows :)

> I'm asking to try and understand your use-case and to try and figure out if/how such a feature could be more generally applicable to the wider user base :)

Thank you so much for asking all of this !!!! It's always a pleasure talking to you :)

Ask anything you want! Lets talk and see if we can bring a new feature to this fantastic plug-in that could help everybody !!!!

---

Just to summarize our links in groups:

Using `foo.md` as the active note

01 - link to external note: `[[bar.md]]`

02 - Embed links: `![[bar.md]]`

03 - Block links `note.md#^blockref`
3.A - internal block `foo.md#^blockref`
3.B - external block `bar.md#^blockref`
3.C - external block header `bar.md#^baz_header`

Options for the Users (I don't know if its feasible):

`Show Links`
- 01

`Show Embeds`
- 02

`Show Block Links Internal`
- 3A

`Show Block Links External`
- 3B
- 3C

Or treat 3C with 01 in `Show Links`

---

Sorry for the long text. I think we are going to find a great new feature :)

**Comment by FelipeRearden** [comment]
Hello @darlal, 

I had an idea yesterday, maybe it's an easier way to implement this than what we have been talking ... :)

How about using the alias `|alias_name` of a block link `bar.md#^blockid|alias_name` as the criteria to show or hide block links 

A field where the user could type (input) the the names of alias to be hidden in the Symbol List Mode.
- maybe something like: `alias_name01;alias_name03;alias_name04` 
- in my case, would be `█;▼;🔖` since I use symbols and emoji as alias to block links.

Maybe it's a good idea:)

Have a great day!

**Comment by FelipeRearden** [comment]
Hello @darlal !

> in addition I think header links fall into the same category as these can be seen as a different sub-set of links.

100% agree with you @darlal !

> I've added this to the project backlog.

Thank you very much for this !!!!!!!!!!!!!!

I wish you a great day!

**Comment by darlal** [comment]
@FelipeRearden this feature has been added in the [1.0.5 release](https://github.com/darlal/obsidian-switcher-plus/releases/tag/1.0.5). Check it out, I will close out this issue.

**Comment by FelipeRearden** [comment]
> @FelipeRearden this feature has been added in the [1.0.5 release](https://github.com/darlal/obsidian-switcher-plus/releases/tag/1.0.5). Check it out, I will close out this issue.

Hello @darlal !!!!!

Thank you very much for this feature !!!! I'm so happy :)

Working perfect on version `1.0.5` Obsidian `0.12.19`

Thanks !!!!!!!!

Have a great day!!!!!
