### ISSUE TITLE
[Feature Request] Open note in new pane by default

### ISSUE THREAD

**Issue by Guilvareux** [darlal/obsidian-switcher-plus#29]
Hi!

I'm working with the 'sliding panes' plugin at the moment. Would an option to open notes in a new pane by default be an easy addition? It'd be great addition here given I can't seem to find it anywhere else.

Cheers

**Comment by darlal** [comment]
I believe the builtin switcher allows you to open in new pane while holding CMD/CTRL. It seems that should work on Switcher++ too, but doesn't currently. Is that what you mean, or, do you mean to always open in a new pane all the time no matter what?

**Comment by Guilvareux** [comment]
Always open a new pane by default was my idea. I'm usually using a few open notes at the same time so it'd just be easier for me to always open a new note and close a few when the times comes.

**Comment by darlal** [comment]
A global default would work for all the custom modes, but wouldn't work for standard mode. Standard mode operations (like opening a file) are handled by the built-in, system switcher. But this would be a good option to add for the custom modes. Thanks!

**Comment by darlal** [comment]
@Guilvareux this feature is live in release [1.0.10](https://github.com/darlal/obsidian-switcher-plus/releases/tag/1.0.10). Thanks!
