### ISSUE TITLE
[Feature Request] Always respect "Auto-select nearest heading" 

### ISSUE THREAD

**Issue by Lazbaj** [darlal/obsidian-switcher-plus#32]
Hi,

the "Auto-select nearest heading" setting is valid when using the "Open in Symbol Mode" command.
However, it should also be respected when simply launching "Quick Switcher++: Open" with a keyboard shortcut and just pressing @ to enter in symbol list mode for the current file.

Thanks,
really great stuff here!

**Comment by darlal** [comment]
Thanks for the report. I think we can get this to work in all cases. I'll add it to the backlog.

**Comment by darlal** [comment]
This issue should be resolved in the [1.0.7](https://github.com/darlal/obsidian-switcher-plus/releases/tag/1.0.7) release.

**Comment by FelipeRearden** [comment]
Working perfect on version `1.0.7` on `Symbol Mode` and the operation described in the FR using `QuickSwicther++:Open`

Thank you very much @darlal for one more amazing update :)

**Comment by Lazbaj** [comment]
It's perfect, thanks!
