### ISSUE TITLE
Allow remove highlight on symbol mode search

### ISSUE THREAD

**Issue by navakelvin** [darlal/obsidian-switcher-plus#33]
In symbol mode search when you select an item it directs you to the item by highlighting it.

The problem: you might think the Esc key would remove the highlight but no, it remains. It is only removed by clicking somewhere in the editor.

Windows 11.
Obsidian v0.13.23

**Comment by darlal** [comment]
@navakelvin I believe this is standard behavior for the core app overall. Clicking on search results from the search pane, or any mentions from the backlinks pane behave the same way. There seems to be two different behaviors, one for `Reading View` and one for `Editing View`.

**Reading View**
Reading view seems to perform the highlighting, but the highlighting disappears automatically after a few seconds.

**Editing View**
Editing view seems to perform the highlighting, and the highlight remains until click

**Comment by navakelvin** [comment]
@darlal Thanks, that explains it all.
