### ISSUE TITLE
[Bug] Can't Open Heading In New Pane

### ISSUE THREAD

**Issue by Signynt** [darlal/obsidian-switcher-plus#35]
When searching for a heading, and then trying to open it in a new pane by hitting `Cmd + Enter` nothing happens.

**Comment by darlal** [comment]
Thanks for the report. The new pane handling of the plugin predates the cmd+Enter paradigm and needs to be reworked. Added to the backlog. Thanks.

**Comment by 23727** [comment]
> Thanks for the report. The new pane handling of the plugin predates the cmd+Enter paradigm and needs to be reworked. Added to the backlog. Thanks.

thank you

**Comment by darlal** [comment]
@Signynt @23727 this is addressed in release [1.0.8](https://github.com/darlal/obsidian-switcher-plus/releases/tag/1.0.8).

**Comment by FelipeRearden** [comment]
> @Signynt @23727 this is addressed in release [1.0.8](https://github.com/darlal/obsidian-switcher-plus/releases/tag/1.0.8).

Working perfect on version `1.8.0`

Thank you very much @darlal !!!!
