### ISSUE TITLE
[Feature Request] New Command = Open + Open in Symbol Mode

### ISSUE THREAD

**Issue by FelipeRearden** [darlal/obsidian-switcher-plus#36]
Hello @darlal !!!!!!!!!!!!!!!!

MY FR is simple to explain: it's a new command that combines two QS++ commands into one:
- Quick Switcher++ : Open
- Quick Switcher++ : Open in Symbol Mode 

Another words: Choose a file to open and after opening the file, automatically bring the Symbol Mode Modal to give us the ability to navigate in the new open file !!!!

## My Workflow

I have a lot of notes that I create to store references/terms from things that I'm learning to remember when I'm working on a specific subject. I call these `Reference Notes`. For example:
- Excel Formulas 
- Regex queries
- iOS Shortcuts
- CSS definitions and selectors 

These notes have a simple structure:

```
## Reference 1

Details about Reference 1

`code`

Explanation about the code

## Reference 2

Details about Reference 2

`code`

Explanation about the code

```

This way, many times I open the note `Open` and hit another hotkey to enter in `Symbol Mode` to start searching about a reference. 
- Most of the time I don't remember the exactly name of the reference, I just know that is inside this note due to the topic that is related.
- This way I can't use only symbol mode directly to search . I have to open the specific note and then go to `Symbol Mode` to search between the readers using the arrows keys 

Since this is something that do many times, I realize that we could have an specific command that merge these two commands :)

## Workaround 

Today to achieve something like this, I'm using a QuickAdd Macro 

![AD898751-D6E5-4478-83A6-2E78C2CD21E9](https://user-images.githubusercontent.com/85180696/156766222-7e258cc3-a59a-494b-8316-48cade0a252c.jpeg)

The problem here is that I have to use a timer between the two commands and some times I'm too fast and other times I forget the name of the note and I lost the time to open the note :(

---

I hope you like my suggestion :)

Thanks for reading this !

Have a great day!!!

**Comment by darlal** [comment]
Hey @FelipeRearden! If I understand your request, you want to be able to open a note, and immediately launch symbol mode to navigate to the right spot within the note. But right now, it's two manual steps:

1. Open the switcher, search/filter for the correct note, then open
2. Open the switcher again (this time in Symbol mode), search/filter for the correct Symbol (heading), then `Enter` to perform the navigation.

You'd like to be able to perform both the note selection/open, and the Symbol selection/navigation all in one step, is that correct?

If that's the case, Switcher++ already supports this use case. You can use any of the File Open modes (`Headings`, `Editor`, `Standard filename`) with an **embedded Symbol mode** and supply a filter for the Symbol navigation. This will enable you to 1) select the correct note, 2) select the desired heading to navigate to all in one go.

Using your example above: 

1. Execute `Quick Switcher++: Open`, type `Excel For` use the arrow keys to highlight the `Excel Formulas` note, but don't hit `Enter` to open it yet
2. With the desired note highlighted in the Switcher result list, type the Symbol mode trigger character (default `@`). The Switcher result list will change to list the Symbols from the highlighted note. You can again filter this list and/or use the arrow keys to highlight the desired symbol. Once highlighted, hit `Enter`, this will both open the note and navigate to the Symbol that was highlighted.

An alternative to consider:
If your references are always grouped under a header like `## Reference 2`, you could just use [Headings Mode](https://github.com/darlal/obsidian-switcher-plus#search-headings-instead-of-filename) directly to filter, open, and navigate to the desired heading directly.

**Comment by FelipeRearden** [comment]
Hello @darlal !!!!

Thank you very much for your reply ! 

Every time that we talk I learn something new :)

What you describe beautifully is exactly what I need !!!!!!!!

Thank you very much ! I didn't know that I could embed Symbol Mode after start my search for a file !!!!! 
- this opens a new world for me to explore, thank for explaining to me. 

> An alternative to consider:
If your references are always grouped under a header like ## Reference 2, you could just use Headings Mode directly to filter, open, and navigate to the desired heading directly.

You are 100% and I use Heading Mode a lot when I know the words that I wrote in `## Reference 2` but I don't remember i the name if the note. For example in Daily Notes, I use `###` to organize some subject that I know I'm gonna search in the future:

```
### Shoes Store 
Street:  lore Ipsum 
Phone:123-546
Person of Interest : Loren ipsum 
``` 

___

Thank you very much @darlal I'm gonna implement this new workflow right now !!!!!

Have a great day !!!!!!
