### ISSUE TITLE
FR: Add class to the Quick Switcher to allow Styling by themes

### ISSUE THREAD

**Issue by chrisgrieser** [darlal/obsidian-switcher-plus#37]
I am a theme dev and would like to theme the prompt by this plugin, however the html elements form this plugin use exactly the same classes as the regular quick switcher. Therefore, it is not possible to properly style this plugin without affecting the other prompts. 🙁 

<img width="798" alt="Screenshot 2022-04-03 12 06 51" src="https://user-images.githubusercontent.com/73286100/161422432-ea3c0993-9db8-4ced-98c9-9c275c1d1c5c.png">

**Comment by darlal** [comment]
Hey thanks for your interest in styling Switcher++! I actually use your theme! 😀 

A main design goal for Switcher++ is to be a "drop in" replacement for the built-in system Switcher. As such, it provides the exact same functionality, and uses the same modal structure as the system switcher, with the extended functionality on top. The common usage is to simply "replace" the system switcher with switcher++. If you create a custom style for the built-in, system switcher, then switcher++ should just reflect that style as well.

**Comment by chrisgrieser** [comment]
> Hey @chrisgrieser, thanks for your interest in styling Switcher++! I actually use the shimmering-focus theme! 😀

😄 💙
(btw, if you update Shimmering Focus, I added some minor styling improvements for QS++ / QS in general in the latest updates.)

> A main design goal for Switcher++ is to be a "drop in" replacement for the built-in system Switcher. As such, it provides the exact same functionality, and uses the same modal structure as the system switcher, with the extended functionality on top. The common usage is to simply "replace" the system switcher with switcher++. If you create a custom style for the built-in, system switcher, then switcher++ should just reflect that style as well.

I know, but the issue is, right now, the QS++ shares the same css classes as the normal QS. While this is desirable so that Quick Switcher styling carries over to QS++, this makes it impossible to apply different styling for cases where different styling may be desirable. For example, both the alias-icon from the regular QS, and the `H1` icons from QS++ use the same cssclass `.suggestion-flair`. However, I was thinking to resize the `H1`, but *not* to resize the alias-arrow-icon. Right now, this is impossible, since they do not have any differentiating cssclass. (for the symbol search, this wasn't an issue, because the symbols do have separate icons.)

Like, it's only a super minor thing, if you have the time at some point 😄

**Comment by darlal** [comment]
Ah ok, the Header icons I can add something to so they can be styled separately since they are part of the "extended functionality" similar to the Symbol icons. I'll get something in there soon. Again, thanks for your work on the theme!

**Comment by chrisgrieser** [comment]
well, thanks *you* for the plugin 😄

**Comment by darlal** [comment]
@chrisgrieser I've added an additional class to the [headings icon](https://github.com/darlal/obsidian-switcher-plus/blob/master/src/Handlers/headingsHandler.ts#L99) to differentiate it. This should go live with the next release. Thanks!

**Comment by darlal** [comment]
And it's live.. release [1.0.8](https://github.com/darlal/obsidian-switcher-plus/releases/tag/1.0.8).
