### ISSUE TITLE
[Bug] Can't use Symbol mode in Editor mode when using multi-character triggers

### ISSUE THREAD

**Issue by JeloKuneho** [darlal/obsidian-switcher-plus#39]
Multi-character triggers work just fine on their own mode but when trying to trigger two modes (like Editor then Symbol mode), it doesn't work.

Steps to reproduce:

1. Set `Symbol list mode trigger` to `@s`
2. Open quickswitcher++ in editor mode or open quickswitcher++ and type `edt`
3. Enter `@s`

**Comment by darlal** [comment]
Thanks for the report. I'll look into this.

**Comment by darlal** [comment]
Symbol mode is a bit special amongst the other modes in that when triggered it operates on the active (currently selected) suggestion in the chooser drop-down. If there isn't an active suggestion, then it operates on the active opened file (WorkspaceLeaf). 

So there's likely something non-obvious happening here, to try and explain let's imagine that the Symbol  Mode trigger was changed to the word `cool`. Then, Open Switcher++ and type `foo`, this will display suggestions for all the files that match `foo`. Now we want to trigger Symbol Mode for one of those files by typing the trigger word `cool`. Start with typing `c`, then `o`, `o`, these will not trigger Symbol Mode, instead what they will do is further refine the list of suggestion to only contain files that match `foocoo`. When the last `l` is typed to complete the `cool` trigger word, then symbol list will be triggered on whatever file happened to be listed and selected as a suggestion before the last `l` was typed. The multi-character trigger word is conflicting with the filter text used to generate suggestions in the first place. This is likely the behavior that you are seeing.
