### ISSUE TITLE
FR: Support Hover Editor's "open in new popover" command in quickswitcher++

### ISSUE THREAD

**Issue by JeloKuneho** [darlal/obsidian-switcher-plus#40]
Hover Editor has a command to open new notes in a popover (https://github.com/nothingislost/obsidian-hover-editor/releases/tag/0.8.0).

<img width="467" alt="image" src="https://user-images.githubusercontent.com/99579095/163738479-3bdf2c2e-1983-4d53-afdb-e90edced2a6a.png">

When I try the command in quickswitcher++, it just moves the selector up.

**Comment by darlal** [comment]
Thanks for the report. Hover Editor is a completely separate plugin from QuickSwitcher++, so it's not surprising that a command from Hover Edit doesn't work in Switcher++. 

From what I can tell by quickly looking at Hover Editor, it adds a [monkey-patch](https://github.com/nothingislost/obsidian-hover-editor/blob/master/src/main.ts#L113) to the builtin Switcher and by extension Switcher++. The monkey-patch requires the selected suggestion to have a ['file' object/property](https://github.com/nothingislost/obsidian-hover-editor/blob/master/src/main.ts#L129) for the custom "open in new popover" command to work properly. Some Switcher++ modes do not have that property, but the modes that do have that property like `Standard` and `Header` modes seem to work properly.

**Comment by darlal** [comment]
This has been addressed in release [1.0.8](https://github.com/darlal/obsidian-switcher-plus/releases/tag/1.0.8). Thanks.

**Comment by FelipeRearden** [comment]
> This has been addressed in release [1.0.8](https://github.com/darlal/obsidian-switcher-plus/releases/tag/1.0.8). Thanks.

Working perfect on version `1.8.0`

Thank you very much @darlal !!!!

🔑 The hotkey to open in Hover Mode is `CMD/CRTL+P`

**Comment by darlal** [comment]
humm.. unfortunately, I don't have a windows machine to test this on. What is the default `open in Hover Editor` hotkey **on Windows** in the **Hover Editor** (not QS++) plugin?

**Comment by FelipeRearden** [comment]
> humm.. unfortunately, I don't have a windows machine to test this on. 

Yeah, I'm MacOS and iPadOS and I use a Windows machine to run some tests (that why I saw) :)

> What is the default `open in Hover Editor` hotkey **on Windows** in the **Hover Editor** (not QS++) plugin?

It's CTRL+P as well. When HE is active, the plugin adds this hotkey to the native Quick Switcher 

Second Bullet in the Release Notes 🔽

https://github.com/nothingislost/obsidian-hover-editor/releases/tag/0.8.0

---

Maybe is something only on my end. Let's see the feedback from our real Windows user :)

Let me know if can help with anything more :)

Have a great day @darlal !!!!!

**Comment by darlal** [comment]
Thanks, yea I see what's happening. Hover Editor monkey patches the system switcher and [injects](https://github.com/nothingislost/obsidian-hover-editor/blob/master/src/main.ts#L126) `mod-p` hotkey. QS++ also [registers](https://github.com/darlal/obsidian-switcher-plus/blob/master/src/switcherPlus/keymap.ts#L24) `ctrl-p/n` as those hotkeys are pretty commonly used for navigating up/down in lists.

**Comment by FelipeRearden** [comment]
I'm glad to know that you found the reason :)
