### ISSUE TITLE
Exclude is NOT working.

### ISSUE THREAD

**Issue by Peingxious** [darlal/obsidian-switcher-plus#42]
I don't know if I don't know how to use it, or what, sometimes it works and sometimes it doesn't work, and I can still find it in the excluded folder.

It can be ruled out at the first time of reload, and useless after re-entry.

**Comment by darlal** [comment]
One thing to note is that the exclude folder function only applies to `Headings` mode. So if you search for an excluded file in Headings mode you should not find it, but if you search for it in `Standard` mode it may still show up. Obsidian 14.6 (iirc) has support for excluding folders globally. That said, it would be great if you could provide some clear steps that I could use to try and reproduce the behavior you are seeing. Thanks.
