### ISSUE TITLE
Accessing backlinks of current file

### ISSUE THREAD

**Issue by Glint-Eye** [darlal/obsidian-switcher-plus#43]
Hello :). I really love this plugin, as it makes keyboard navigation through your vault so much easier.

I'd have one feature suggestion.

So far i've found no way to interact with backlinks without using the mouse pointer.

It would be great if backlinks could be accessed through quick switcher++ (at least in a capacity to see the file names for backlinked files. unmentioned links would be a great plus too.) a seperate shorthand character and hotkey would be great too.

Cheers and thx for the great plugin :)

**Comment by darlal** [comment]
Thanks, I'm glad you're finding the plugin useful.

Adding forward/backlinks to the switcher is something that I've [considered before](https://github.com/darlal/obsidian-switcher-plus/discussions/21). I wasn't sure if a) it would be useful for folks, b) if only having access to the filenames would be sufficient. Sounds like you feel it would be useful, thanks for the feedback.

**Comment by woshitoutouge** [comment]
+1

> Hello :). I really love this plugin, as it makes keyboard navigation through your vault so much easier.
> 
> I'd have one feature suggestion.
> 
> So far i've found no way to interact with backlinks without using the mouse pointer.
> 
> It would be great if backlinks could be accessed through quick switcher++ (at least in a capacity to see the file names for backlinked files. unmentioned links would be a great plus too.) a seperate shorthand character and hotkey would be great too.
> 
> Cheers and thx for the great plugin :)

**Comment by PaulWen** [comment]
+1

Would love to have this type of navigation too :)

**Comment by darlal** [comment]
This is live in [release 2.2.0](https://github.com/darlal/obsidian-switcher-plus#related-items).
