### ISSUE TITLE
FR: Switcher that only displayed files in the current folder

### ISSUE THREAD

**Issue by chrisgrieser** [darlal/obsidian-switcher-plus#44]
pretty much what the title says, I think that might be a good fit for the plugin?

Also opening an issue at the repo of another quick Switcher, since It would also fit that plugin (I am using both anyway 😝 ).

**Comment by darlal** [comment]
Thanks for the feature request. There's a similar request already #25 which I'm planning to work on as soon as time allows. Please upvote that one as well, and I will close this one as duplicate.

**Comment by chrisgrieser** [comment]
I, missed that one. Thanks, will do!

**Comment by darlal** [comment]
@chrisgrieser no problem. btw I noticed you had an FR and Templater script to show starred items. This is something that I added recently to this plugin as well in the [1.0.7 release](https://github.com/darlal/obsidian-switcher-plus/releases/tag/1.0.7).

**Comment by chrisgrieser** [comment]
thanks you 😊

**Comment by FelipeRearden** [comment]
> There's a similar request already #25 which I'm planning to work on as soon as time allows.

🙏 🙏 🙏

**Comment by darlal** [comment]
@chrisgrieser this feature is live in [release 1.0.9](https://github.com/darlal/obsidian-switcher-plus/releases/tag/1.0.9). Happy note-taking!
