### ISSUE TITLE
[bug] can not find filename `oauth`

### ISSUE THREAD

**Issue by Jackiexiao** [darlal/obsidian-switcher-plus#45]
see picture

but when I search `obsidian`, it could find file named obsidian
![image](https://user-images.githubusercontent.com/18050469/166212966-e41a1dc1-ec6e-460f-afac-2eb452210812.png)

**Comment by darlal** [comment]
A couple questions to help diagnose..

1. Is that file excluded via the Obsidian exclude folders list? `settings->Files & Links->Exclude Files`?
2. Is that file excluded via the Switcher++ exclude folder list? `Switcher++ settings->Headings List Mode->Exclude folders`
3. Is it a markdown file? does it have an H1 containing the word `oauth`? It should fallback to searching the filename as well, but these matches get down-ranked.
4. Does the file show up when you search in `Standard Mode`?

Thanks!

**Comment by Jackiexiao** [comment]
thx for your reply!
1. No
2. No
3. It is a markdown file, it does not have an H1 containing the word `oauth`
4. yes, it shows up

**Comment by darlal** [comment]
Humm.. interesting. More questions:

1. What version of the Switcher++ plugin are you running `Settings->Community plugins->Installed Plugins`? and what version of Obsidian `Settings->About`?
2. The list of result can be scrolled, are you sure that the file doesn't appear anywhere in the result list? As I mentioned, when the fallback to filename is triggered, those matches get down ranked, so it could appear lower in the result list (below the immediately visible results)
3. Is that file nested in some folder hierarchy?
4. Do results show up for searches of other markdown files that are in the same folder as the `oauth` file (sibling to the oauth file)?

A couple things to try for testing purposes:

1. Add an H1 with some unique text to that file, restart Obsidian, then see if it will show up in the result list.
2. If it is nested in a folder hierarchy, try moving it to the root of the vault, restart Obsidian, then try the search again to see if it shows up.

Thanks!

**Comment by Jackiexiao** [comment]
1. `1.0.7` version，obsidian version is `v0.14.9`
2. yes, I am sure that the file doesn't appear anywhere in the result list
3. this file is in `docs/notes/oauth`
4. yes, but not all of them, some files don't show in result list just like `oauth`, but I can't find any relation by myself, it seems this bug occur randomly

testing
1. yes, it shows up in the result list, and no need to restart obsidian
2. no, it won't show up in the result list

however, I can finally reproduce the bug, when I create new file and add `h1` header, it won't shows up in the result list, but when delete `h1` and add `h2` header, new file shows up in the result list

**Comment by darlal** [comment]
ah ok, so the file does contain an `h1` header. I'm going to guess that you also have the Headings Mode setting `Show headings only` disabled. This is actually expected behavior.

The way it works current is if you have `Show headings only` disabled **and** the file does **not** contain an `h1` heading, then it will fallback to searching against the filename. The idea being that the `h1` serves as the "title" and if the title is missing then fallback to searching the filename.

An alternative approach could be to fallback to filename search whenever there is zero matches against headings, but I would need to think through the implications of that kind of a change.

**Comment by Jackiexiao** [comment]
ok, thx for your reply, I think ` fallback to filename search whenever there is zero matches against headings` is great

**Comment by darlal** [comment]
@Jackiexiao this is live in release [1.0.10](https://github.com/darlal/obsidian-switcher-plus/releases/tag/1.0.10). Thanks!
