### ISSUE TITLE
Please add a "Recent Files" mode

### ISSUE THREAD

**Issue by Randy-Astle** [darlal/obsidian-switcher-plus#46]
Really like quick switcher plus -- especially the different modes. 

There is a Recent Files extension that I've found useful. However, it would be even more convenient if the list of recent files was available via a new quick switcher plus mode. It would be fine to have a dependency on the Recent Files extension being installed before this mode could be used.

**Comment by darlal** [comment]
Glad you find the plugin useful!

Switcher++ does show the list of recent files by default when opened in `headings` mode (with no search/filter text). It's not a separate mode currently, mainly because iirc Obsidian only tracks 10 most recent files at most.

**Comment by Randy-Astle** [comment]
Ah... :-)
Didn't realize that.

Thanks.
