### ISSUE TITLE
[FR] filter result by fuzzy search on filename

### ISSUE THREAD

**Issue by Jackiexiao** [darlal/obsidian-switcher-plus#47]
for example, I have a lot of file contain `# TODO` heading

![image](https://user-images.githubusercontent.com/18050469/167076045-f19849a9-251a-408f-b4c8-cf57e76488a7.png)

I would like to enter `filename` to quickly find what I actually want (filter result), because there is too many result, up and down key would be inconvenient

**Comment by darlal** [comment]
`Standard` mode prioritizes filenames, and works exactly the same as the default system switcher. In your example, if you just delete the `#` sign, so change from `#todo` to just `todo`, that will search against filenames instead. Please let me know if you meant something different here.

**Comment by Jackiexiao** [comment]
I think this issue is duplicate with https://github.com/darlal/obsidian-switcher-plus/issues/48, so I close it.

yes, delete `#` works, but it is a little inconvenient
