### ISSUE TITLE
[FR] remnote like search

### ISSUE THREAD

**Issue by Jackiexiao** [darlal/obsidian-switcher-plus#48]
ok, I think this maybe too more for this plugin, but I really need a general search like remnote software, it combind `ctrl + O` with `ctrl shift F`, so you can search and jump to anywhere. Of course, filename and title would be first class citizen (should show up first)

it also have `tree` search, for example, you can search filename first and then `tab` to search heading or any content in the file you selected before

**Comment by darlal** [comment]
Thanks for the feature request.

A general search is beyond the scope of this plugin for the time being. I'm not familiar with remnote, but I think there is an existing plugin that enables search via a quick switcher style interface [obsidian-omnisearch](https://github.com/scambier/obsidian-omnisearch).

For the second part, again I'm not familiar with remnote, but Switcher++ does allow you to "index" into a file and navigate to Symbol content (Headings, Tags, Links, etc..) right from the switcher. Check out the [docs](https://github.com/darlal/obsidian-switcher-plus#symbol-navigation-headings-hashtags-links-embeddings).

![demo](https://raw.githubusercontent.com/darlal/obsidian-switcher-plus/master/demo/symbol-mode.gif).

**Comment by Jackiexiao** [comment]
wow! [obsidian-omnisearch](https://github.com/scambier/obsidian-omnisearch) and `filename@title` format is great!!

I think remnote's search is combination of `obsidian-omnisearch` and `switcher-plus`, but better, FYI

![image](https://user-images.githubusercontent.com/18050469/167234376-c6e26afc-23da-4fd7-95e8-7d0de9070bc5.png)

![image](https://user-images.githubusercontent.com/18050469/167234366-5d397c65-f9e9-4dba-902c-84ff0031718b.png)

maybe I will upload a gif later

**Comment by darlal** [comment]
>wow! [obsidian-omnisearch](https://github.com/scambier/obsidian-omnisearch) and filename@title format is great!!

Awesome! use them together 😄 

>I think remnote's search is combination of obsidian-omnisearch and switcher-plus, but maybe better, FYI

Thanks for the screenshots. Switcher++ is a work in progress, maybe we'll get there someday 😄 For now, I'm going to close this issue. Thanks!
