### ISSUE TITLE
[Feature Request] Vim-Like Navigation Keys for Switcher Search Results

### ISSUE THREAD

**Issue by julroger2013** [darlal/obsidian-switcher-plus#50]
It would be helpful to use Vim-like hotkeys—such as J & K—to navigate search results from Quick Switcher ++

**Comment by darlal** [comment]
@julroger2013 Thanks for the feature request! This is straightforward, I'll add it to the backlog. It would need to be cmd/ctrl-j/k since you'd need the actual j/k keys for typing.

**Comment by darlal** [comment]
@julroger2013 this is live in release [1.0.11](https://github.com/darlal/obsidian-switcher-plus/releases/tag/1.0.11). Thanks!
