### ISSUE TITLE
[Feature Request] Separate File/Folder Path & File Name for Search Purposes

### ISSUE THREAD

**Issue by julroger2013** [darlal/obsidian-switcher-plus#51]
The current search results in Quick Switcher ++ show the full path of a particular result. 

In my Vault, for instance, today's daily note displays as 01 Inbox/2022/05-May/22.05.09

This can make search results a little hard to read, particularly for those of us who use deeply-nested folders. Would you consider having the file path— 

(1) As a feature that can be toggled on or off. 
(2) Displayed separately from the file name (perhaps below the file, the same way that Aliases/File Names are currently rendered together, or, alternatively, displayed separately from the file name along the righthand margin of the search results window).

**Comment by darlal** [comment]
@julroger2013 thanks for the feature request! I think Headings mode does this already, except for when it's a file/alias suggestion. A feature toggle can definitely be added for that. Thanks!

**Comment by julroger2013** [comment]
Your latest release seems to indicate that this feature should now be present (in terms of hiding path, etc.). But I've tried adjusting that toggle to no effect. Perhaps it hasn't been fully rolled out yet—or, more likely, I've just misunderstood what the release notes were saying. 

But I thought I'd flag this for you in case things were supposed to be working this way but aren't.

**Comment by darlal** [comment]
Your feature request hasn't been implemented. The most recent releases addresses a different request, and is a precursor to your request. It's coming soon though. Thanks.

**Comment by julroger2013** [comment]
Ahh yes I can see that now. It was for a different search mode. 

Thank you for clarifying!

**Comment by darlal** [comment]
As of [release 2.0.3](https://github.com/darlal/obsidian-switcher-plus/releases/tag/2.0.3) the filename/path rendering should be separated in all custom modes where it makes sense `editor`, `headings`, `related items` and `starred`. Thanks!

**Comment by julroger2013** [comment]
This is wonderful, and is exactly what I was thinking of. 

Could I suggest adding this option (perhaps with a toggle, perhaps not—whichever you think is best!) for the ordinary Quick Switcher mode, too? 

The way that the "Quick Switcher ++: Open" command handles aliases right now is exactly what I'm thinking of. It shows just the alias on top, followed by the entire path below. It would make sense to me to display the non-alias title exactly the same way: the title on top, with the entire path (including the title) below. 

My file names generally aren't duplicative between different paths, so seeing the entire path name alongside the title usually isn't too important for me. 

Thank you for the implementing this the way you have for editor, headings, related items, and starred. It looks great and really does reduce visual clutter!
