### ISSUE TITLE
How can i search attachments file like PDF?

### ISSUE THREAD

**Issue by chumido98** [darlal/obsidian-switcher-plus#54]
As title. Can someone help me? The result is only notes.

**Comment by darlal** [comment]
@chumido98 there are some Obsidian setting that you should ensure are enabled to have PDFs and other file types show up.

**Detect al file extension**
Options->Files & Links->Detect all file extension

**Show all file types and Show attachments**
Options->Quick Switcher (note: _not Quick Switcher++_)->Show all file types
Options->Quick Switcher (note: _not Quick Switcher++_)->Show attachments - this one for PDFs specifically

If all those options are enabled, and you have PDF files in your vault, then they should show up in the switcher. Let me know if that helps.

**Comment by chumido98** [comment]
That helps. Thank you very much.
