### ISSUE TITLE
[FR] Filter tags globally

### ISSUE THREAD

**Issue by twio142** [darlal/obsidian-switcher-plus#55]
I'd love to have a 'tag mode' which allows to search for any specific tag and then list all notes containing it.

It'd surprise me if no one has asked for this yet... Unless it's already implemented and I just never figured out..?

**Comment by darlal** [comment]
@twio142 there is another plugin that does have support for tags already, see [Another Quick Switcher](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher).

**Comment by rdoering** [comment]
@twio142 thanks
Unfortunately, I have to switch, now.

**Comment by darlal** [comment]
You can actually use both at the same time, many people do. They don't conflict with each other.
