### ISSUE TITLE
[Feature Request] Symbol Mode - Support for Obsidian Callouts

### ISSUE THREAD

**Issue by FelipeRearden** [darlal/obsidian-switcher-plus#57]
Hello @darlal  !!!!!

My FR is simple to explain: A new item to the spectacular `Symbol Mode` —> Obsidian Callouts !!!!
- Show Callouts

![A3D42EC9-5670-4A46-BF7B-19A22694E3D1](https://user-images.githubusercontent.com/85180696/172062818-79493260-4dd3-4f7f-b4aa-5d803e63f93e.jpeg)

⚠️ I don’t know if is feasible but would be a great addition to the Symbol Mode :)

## My Idea

If the Callout have Title  >>> Symbol Mode list will show the **title** `Lorem Ipsum`

![55BBC1E1-78FF-461C-AC94-EAB6A5F103AC](https://user-images.githubusercontent.com/85180696/172062876-5fc88356-4a3c-471e-96de-c8205721848e.jpeg)

If the Callout DONT have a Title  >>> Symbol Mode list will show the **callout type**  `NOTE`

![A1A76C46-2D9D-4BD8-B0E9-5E3880B4E140](https://user-images.githubusercontent.com/85180696/172063077-d13c44a7-b357-4e77-9314-540baf61d5bb.jpeg)

---

Since we use callouts to store/write important items of a note, I think would be great to be able to open Symbol Mode and navigate directly to the content inside a Callout :)

Thanks for reading this !!!!

Let me know what you think :)

Have a great day @darlal !!!!!!!

**Comment by darlal** [comment]
From a quick look, it seems that there is some Callout information in the metadata, so I think this is doable. I'll add it to the backlog. Thanks.

**Comment by FelipeRearden** [comment]
Thank very much @darlal for considering this FR for the next version in the future !!!!!

Will be amazing to navigate between Callouts :)

Have a great day !!!!!

**Comment by darlal** [comment]
Hey @FelipeRearden  this feature is live in release [2.0.6](https://github.com/darlal/obsidian-switcher-plus/releases/tag/2.0.6), note this requires Obsidian version `0.15.9`

**Comment by FelipeRearden** [comment]
> Hey @FelipeRearden  this feature is live in release [2.0.6](https://github.com/darlal/obsidian-switcher-plus/releases/tag/2.0.6), note this requires Obsidian version `0.15.9` 

Working perfect on version 2.0.6 on Obsidian 15.9 and Obsidian Mobile 1.3.1

I really liked that you keep the color of the border of Callout in the modal 💙

Thank you very much @darlal !!!!!
