### ISSUE TITLE
[Feature]  Show path in editor mode

### ISSUE THREAD

**Issue by dexx086** [darlal/obsidian-switcher-plus#59]
Currently in editor mode (with "edt" command) only the note (file) names are shown, but no path is visible.

It's a good idea to focus on the filenames only (lot easier to read), but to me it happens that I have multiple notes with the same name, but in different folders. In such case, I see these note names multiple times as desired, but I cannot decide which note is on which path.

Is it possible to show the paths of these files next to the file names, maybe with a smaller font type? Like (where "thoughts" is the multiple occuring filename): `"thoughts (/notes/today/thoughts)"` where the `(...)` brackets part could be with a smaller font.
Or maybe should show the path only in cases when there are multiple notes with the same name? Or even better to have an setting for it?
Would be great if some enhancement is achievable.

**Comment by darlal** [comment]
Hey @dexx086 this feature is live with release [1.0.12](https://github.com/darlal/obsidian-switcher-plus/releases/tag/1.0.12). Editor suggestions will show the file path, and you can control how the path information is formatted in the settings. Thanks.

**Comment by dexx086** [comment]
@darlal Wow, it was a quick response and implementation! I really like the multiple options and the look! Thanks.
This plugin just got even more awesome :)

One more question though: do you see a valid need for one more option, like "Full path without filename"?

The reason I'm asking is, because with the "edt" mode the filename is already visible (as it was before), and with the "Full path" option the filename displayed in the path as well (so twice). And if somebody has long note names, it's a bit hard to read the full path looking only for the containing folder of the note.
I know with my example I just did the same, but in action, I just noticed it could be a bit more shorter and readable.

So for the proposed new option, the full path of the note's **folder** would be enough, no need to repeat the filename.
So in my example the visible path under would be only `/notes/today/` (with ending /, it's important to see it's a folder).
However, I think it should work like this only in cases where the found item is a real note's **filename**, because in Heading mode, the items are names of the headings, not the filename, so in these cases still the full path should be visible or else couldn't see the file.

I'm quite happy and can live with the 'Full path' option, I'm just curious if you think my extra option is reasonable and easily implementable or not.

**Comment by darlal** [comment]
Thanks for the feedback. I can see your point about the filename effectively being displayed twice. I'll give this some thought for future consideration. 

Glad you're finding the plugin useful, thanks!

**Comment by dexx086** [comment]
@darlal Thank you! You're awesome. I don't have insider access for v0.15, when it gets publicly accessible, I'll try it, but I'm sure the new option will work great :)

**Comment by dexx086** [comment]
@darlal Thanks again, it's working beautifully :)
