### ISSUE TITLE
edit mode functionality missing

### ISSUE THREAD

**Issue by manogna4** [darlal/obsidian-switcher-plus#6]
When symbol mode is used in with the file in edit mode, the relevant symbol is scrolled into view and gets highlighted, but the file cannot be edited anymore with the keyboard. I have to click on the note with the mouse to start editing again.

This is on Windows 10

**Comment by manogna4** [comment]
When symbol mode is used in with the file in edit mode, the relevant symbol is scrolled into view and gets highlighted, but the file cannot be edited anymore with the keyboard. I have to click on the note with the mouse to start editing again.

This is on Windows 10

**Comment by darlal** [comment]
Hey @manogna4 this is actually default behavior for Obsidian. Perform a search then click on one of the results and you'll see the same behavior. There is a way to enable keyboard focus, but it's not exposed in the plugin settings yet. I'll prioritize that higher up.

**Comment by manogna4** [comment]
I see. I had noticed the behavior you point to, but didn't make the connection. Thank you.

**Comment by darlal** [comment]
I pushed an update that addresses a few things and exposes a new setting. This is now default behavior for the quick switcher is 0.9.17!

**Comment by manogna4** [comment]
excellent. I am not an insider, so I am still on 0.9.15, but I see the change in this behavior. 👍

**Comment by darlal** [comment]
Cool, I'll keep this issue open until 9.17 is public then.

**Comment by manogna4** [comment]
0.9.17 is public, and I see the change in behavior as intended

**Comment by darlal** [comment]
Cool, I will close this issue then.
