### ISSUE TITLE
[Feature Request] Open file in new window

### ISSUE THREAD

**Issue by derekvan** [darlal/obsidian-switcher-plus#60]
Would love to be able to pop open a new window with the file selected in switcher plus. Like with the popover option added recently. Thanks! I love this plugin, especially the ability to view headings.

**Comment by darlal** [comment]
Glad you're finding this plugin useful. I can add a hot key to `open in new window`, similar to the `open in new pane` option that already exists.

**Comment by darlal** [comment]
Hey @derekvan this feature is live in [release 2.0.2](https://github.com/darlal/obsidian-switcher-plus/releases/tag/2.0.2). Note that this requires Obsidian version `0.15.5`. Thanks!

**Comment by derekvan** [comment]
@darlal that's great! Thanks so much. I've updated (15.5 and 2.0.2) and restarted obsidian, but I don't see the option for opening in a new window ...
<img width="700" alt="Screen Shot 2022-07-10 at 3 02 27 PM" src="https://user-images.githubusercontent.com/890341/178158442-c870b4dd-d4fa-4813-bdd1-28e7141dd368.png">

**Comment by darlal** [comment]
It should show up for the custom modes (`headings`, `editor`, `related items`, `starred`, `symbol`) of the switcher. Here's how it should look for headings modes for example. Let me know if you're still having issues. Thanks

![image](https://user-images.githubusercontent.com/5191776/178159111-1b87d3ac-0358-48e2-beb7-1f33b3cc00d2.png)

**Comment by derekvan** [comment]
ok, great I see it now. Is there a design reason to prevent it from working in the main mode? Or maybe because I have `CMD-O` bound to quick switcher plus already it won't take? The `CMD-O` shortcut does work fine for me in the custom modes.

**Comment by darlal** [comment]
SwitcherPlus is designed to be a "drop-in" replacement for system, built-in switcher, as such, it tries really hard to not modify the system functionality as a principle. If you want file suggestions, check out the [Search filenames](https://github.com/darlal/obsidian-switcher-plus#search-headings-configuration) setting that will show file suggestions alongside the heading suggestions.

**Comment by darlal** [comment]
Note: the Tab navigation shortcuts should work in `Standard` mode with [release 2.3.1](https://github.com/darlal/obsidian-switcher-plus/releases/tag/2.3.1) even though they are not listed in the prompt instructions yet.
