### ISSUE TITLE
[bug] update obsidian to v0.15.8, shift+enter not working

### ISSUE THREAD

**Issue by Jackiexiao** [darlal/obsidian-switcher-plus#64]
obsidian: v0.15.8
quick switcher++: 2.0.3

shift + enter doesn't create new note

**Comment by darlal** [comment]
Shift+enter to create a new note is expected to work in `standard` mode. Please let me know if you are seeing issues with this in standard mode.

In custom modes, this is not expected to work as such feature was never implemented. It raises some interesting questions around what the defined behavior should even be in the custom modes. Related to this is the fact that plugins like Templater, and QuickAdd are tailored for managing the note creation process and much better suited for it. Interested to hear your thoughts on it though. Thanks!

**Comment by Jackiexiao** [comment]
yes, `standard` mode (`Quick Switcher++: Open`) works fine

here is my use case, you need to follow the steps to reproduce the bug, I use `Quick Switcher++: Open in headings mode`, I search 
![image](https://user-images.githubusercontent.com/18050469/180668723-bfaac436-3c05-49f1-9a73-395cd463d72a.png)

So I delete `#` to switch to "standard mode"
![image](https://user-images.githubusercontent.com/18050469/180668771-fd785e31-5b9d-4b51-b888-b82510514425.png)

`Enter` to create a new one works fine, but in case something match but I still need to create note using `Shift + Enter`, it doesn't create new note.

As for custom modes, I think it's great to have `shift + Enter` work in `heading mode` so I don't need to delete `#` and create note

**Comment by darlal** [comment]
Thanks for the additional details to help reproduce, I will look into this. Thanks!

**Comment by darlal** [comment]
There's definitely a bug here, We'll get this fixed up in the next release. Thanks!

**Comment by darlal** [comment]
@Jackiexiao the bug part of this issue should be fixed in the new [2.0.5 release](https://github.com/darlal/obsidian-switcher-plus/releases/tag/2.0.5). Please upgrade to get the fix.

I've created issue #67 to track the new feature request. Thanks!
