### ISSUE TITLE
Opening an existing editor mode does not activate the window

### ISSUE THREAD

**Issue by pjeby** [darlal/obsidian-switcher-plus#65]
When selecting an editor that is open in another window, Obsidian remains focused on the window where the dialog was opened.

(This is because setActiveLeaf must be called with a true `focus` parameter if you want to activate the window as well as the leaf.)

**Comment by darlal** [comment]
Thanks for the report. Definitely a bug, will look to get this fixed.

**Comment by darlal** [comment]
@pjeby this should be fixed in [release 2.0.4](https://github.com/darlal/obsidian-switcher-plus/releases/tag/2.0.4). Thanks!

**Comment by pjeby** [comment]
Thanks.  By the way, you don't need to do all those getMostRecentLeaf calls to get the active leaf: `getActiveViewOfType(View).leaf` is an officially ok alternative.

**Comment by darlal** [comment]
Thanks for the tip! I did look at that api, but if I remember correctly `getActiveViewOfType` requires an a view argument, so you would have to know upfront the type of view that you're looking for. For my usecase I don't have that information upfront. In essence, I just need to know what is the current leaf that has focus across all splits, regardless of view type.

**Comment by pjeby** [comment]
No, I mean *literally* ask for a view of type `View` - all views are subclasses of `View` so you will *always* get the current view that way.

**Comment by darlal** [comment]
You're right, it does work. Thanks!
