### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by hungquoc1410** [darlal/obsidian-switcher-plus#66]
The plugin isn't doing what it is supposed to do.
I opened Quick Switcher++ in Symbol mode and nothing shows up. The same for other modes.
<img width="1440" alt="Screen Shot 2022-08-02 at 8 23 48 AM" src="https://user-images.githubusercontent.com/87603881/182271775-45d02a76-29e5-4c1e-9a8f-458083fe1c0c.png">

**Comment by darlal** [comment]
Hey @hungquoc1410 Happy to help you get this working. 

1. What version of Obsidian are you running?
2. What version of the plugin do you have installed?

It's a bit difficult to gather much from the screenshot as it just looks like the default system switcher. Try this:

1. Open a note in the main editor panel, just like you have in your screenshot
2. Open the Obsidian `Command Palette`, note that is is different from the Obsidian `Quick Switcher`. To open the `Command Palette`, by default there should an `Open command palette` icon in the left ribbon, or use the `⌘P` (on the mac) shortcut
3. With the `Command Palette` open, type `++editor mode`, this should hopefully show you only one suggestion - `Quick Switcher++: Open in Editor Mode`, click on that suggestion
4. This should trigger the QuickSwitcher++ editor mode, showing you a list containing the name of the note that you opened back in step 1

If that works, it likely means that initially you were triggering the default system switcher, and not Switcher++. Most people just un-assign the default switcher hotkey, and reassign it to Switcher++ instead. Switcher++ is designed to be a drop in replacement, so you won't lose any functionality by not using the default system switcher.

**Comment by hungquoc1410** [comment]
Hey @darlal 
I did what you asked and it didn't work.
FYI, I am using Obsidian v0.15.9 and I installed version 2.0.4 of the Quick Switcher Plus plugin.
I tried uninstall and install both Obsidian and the plugin but it didn't help.
The plugin was running smoothly before, I don't why it didn't this time.

**Comment by darlal** [comment]
> The plugin was running smoothly before, I don't why it didn't this time.
That is really, really odd. The plugin wouldn't just stop working on it's own, unless something changed.

> I did what you asked and it didn't work.

- Which step didn't work? 
- Where you able to open the `Command Palette`? 
- With the Command Palette open, where you able to filter to just the `Quick Switcher++: Open in Editor Mode` command?
- If so, what happened once you activated that command?

Another thing to try: See if the plugin is being loaded at all by enabling the `Debug startup time` option

1. Open the Obsidian preference pane, navigate to the "Community Plugins" tab, then turn on `Debug startup time`
2. Restart Obsidian
3. Open the Dev Console: View menu, then `Toggle Developer Tools`
4. It should show a listing of all the plugins that were loaded. Does `darlal-switcher-plus` show up in the list? please post a screen shot. Thanks.

**Comment by hungquoc1410** [comment]
I was able to open the `Comman Pallete`, filter to just `Quick Switcher++: Open in Editor Mode`. Once I activated it, it came up as shown below.

<img width="1440" alt="Screen Shot 2022-08-05 at 8 18 13 AM" src="https://user-images.githubusercontent.com/87603881/182981221-40ff8bb9-8661-4494-adce-5a6f9ca64ff9.png">
![Screen Shot 2022-08-05 at 8 18 13 AM (2)](https://user-images.githubusercontent.com/87603881/182981233-a0dc262b-f5b4-4452-bfa7-21439eec8a07.png)

<img width="1440" alt="Screen Shot 2022-08-05 at 8 18 22 AM" src="https://user-images.githubusercontent.com/87603881/182981237-dd6d3355-cbbf-4828-93ae-9988d84d0fd6.png">
![Screen Shot 2022-08-05 at 8 18 22 AM (2)](https://user-images.githubusercontent.com/87603881/182981244-fc0a1636-c6cd-43bc-91b4-7795a9e808cd.png)

As for the `Debug startup time`, the plugin did show up. I attached the screenshot below.

<img width="541" alt="Screen Shot 2022-08-05 at 8 16 09 AM" src="https://user-images.githubusercontent.com/87603881/182981007-0120dc9a-9b3e-4c57-bfd2-3b7a6b777f5a.png">

**Comment by darlal** [comment]
Thanks. So it looks like the plugin is being loaded - which is good. Your second screenshot is again showing the builtin switcher.

Separately, open the dev tools window, and run through the first set of steps to open in Editor mode again please. I would expect to see some messages logged to the console. Please post a screenshot of the full console.

**Comment by hungquoc1410** [comment]
Is this what you are looking for?

<img width="1440" alt="Screen Shot 2022-08-05 at 8 43 49 AM" src="https://user-images.githubusercontent.com/87603881/182983782-7c9443af-f48f-4eb7-88ff-5f4170162469.png">

**Comment by darlal** [comment]
Yes, thank you. This gives us something to work with, I'll look into this. Thanks.

**Comment by hungquoc1410** [comment]
Glad I can help.

**Comment by darlal** [comment]
@hungquoc1410 this issue should be fixed in the new [2.0.5 release](https://github.com/darlal/obsidian-switcher-plus/releases/tag/2.0.5). Please upgrade to get the fix, thanks!
