### ISSUE TITLE
[bug report] Auto-select nearest heading not working well if there are too many headings

### ISSUE THREAD

**Issue by woshitoutouge** [darlal/obsidian-switcher-plus#68]
symbol mode, if there are too many headings in one file, then the auto-select nearest heading function don't work well (picture 2)

<img width="963" alt="1" src="https://user-images.githubusercontent.com/99337435/184333307-0158a3df-9f42-4952-9dc1-6bab5bda56eb.png">

<img width="971" alt="2" src="https://user-images.githubusercontent.com/99337435/184333257-c7d37375-e705-4a93-800a-59b3cf90765b.png">

**Comment by darlal** [comment]
Thanks for the report. We'll check this out.

**Comment by woshitoutouge** [comment]
I updated the plugin and it's working great! Thanks a lot!
