### ISSUE TITLE
Cycle through note list with TAB and SHIFT + TAB

### ISSUE THREAD

**Issue by Randy-Astle** [darlal/obsidian-switcher-plus#69]
It would be very useful if the user could cycle forwards and backwards through the note list with TAB and SHIFT + TAB, respectively.

Randy

**Comment by darlal** [comment]
Thanks for the feature request. Currently there are several other options for navigation, using the arrow keys, ctrl-n/p, as well as ctrl-j/k.

**Comment by darlal** [comment]
This will likely not be implemented as in the future the tab key will be used to enable a different feature. Thanks.

**Comment by darlal** [comment]
For posterity.. Release [3.3.4](https://github.com/darlal/obsidian-switcher-plus/releases/tag/3.3.4) externalizes the navigation keys out to the plugin settings file. The plugin settings file will have to be modified directly, but at least there's a  way of making this change now. If you're comfortable modifying a text json file, try the following:

1. Update to the latest release
2. Navigate to the Switcher++ settings pane in Obsidian. Toggle any of the settings on/off again, this is just to force Obsidian to write to disk an updated settings file.
3. Close Obsidian
4. Make a backup copy of the Switcher++ settings `data.json` file. That file is typically stored in `vault-root/.obsidian/plugins/darlal-switcher-plus/data.json`
5. Open the `data.json` file in a text editor
6. Search for the key `nextKeys`, there should only be one match, which should be nested under a `navigationKeys` key.
7. You'll want to modify/remove the `nextKeys` and `prevKeys` pairs

By default, `nextKeys` defines `ctrl+n` and `ctrl+j`, it might look like this:

```
    "nextKeys": [
      {
        "modifiers": [
          "Ctrl"
        ],
        "key": "n"
      },
      {
        "modifiers": [
          "Ctrl"
        ],
        "key": "j"
      }
    ],
```

And when you're done, you want it to look like this:

```
    "nextKeys": [
      {
        "modifiers": [],
        "key": "Tab"
      },
      {
        "modifiers": [
          "Ctrl"
        ],
        "key": "n"
      },
      {
        "modifiers": [
          "Ctrl"
        ],
        "key": "j"
      }
    ],
```

Notice that a new definition has been added for `Tab` with an empty `modifiers` array. Follow the same editing steps for `prevKeys` to add `shift+Tab`, you want it to look like this:

```
    "prevKeys": [
      {
        "modifiers": [
          "Shift"
        ],
        "key": "Tab"
      },
      {
        "modifiers": [
          "Ctrl"
        ],
        "key": "p"
      },
      {
        "modifiers": [
          "Ctrl"
        ],
        "key": "k"
      }
    ]
```

Save the data.json file, restart Obsidian. This should allow you to navigate next/previous in the switcher with `Tab/shift+Tab`.
