### ISSUE TITLE
new note Creation with Case in-sensitive input

### ISSUE THREAD

**Issue by ebal5** [darlal/obsidian-switcher-plus#7]
When I want to create new note with this plugin, I must input Case sensitive path strings.
But, plugin shows that matching is not case sensitive.

So I think, if there is one and only one choice for the path, isn't it OK to creating a new note with case insensitive input?

**Comment by darlal** [comment]
Thanks for reporting. I'm not sure I completely follow the issue. Are you saying that filtering is case insensitive but that creating a new file on disk based on a filter string is case sensitive?

It would be great if you could post a screenshot. In the meantime, I'll take a deeper look.

**Comment by ebal5** [comment]
Sorry for late replay.

## premise
Open Obsidian's help as vault.

## Current
1. Open Quick Switcher ++
2. type "advanced topic" (fig1) ![type "advanced topic"](https://user-images.githubusercontent.com/6240240/100064280-a76e3100-2e75-11eb-855d-dc421e44109e.png "fig1. after typing 'advanced topic'") 
3. got only one path to folder (named Advanced topic)
4. type "insider builds" (fig2) ![type "insider builds"](https://user-images.githubusercontent.com/6240240/100065051-a8539280-2e76-11eb-86c5-3ffcc962b0e1.png "fig2 after typing 'insider builds'")
5. got only one path "Advanced topics/Insider builds"

## So I think
same as procedure 4, I type "insider creators", I got 
![scr_2020-11-24T16:50:12+09:00_aNxa](https://user-images.githubusercontent.com/6240240/100065581-4b0c1100-2e77-11eb-8466-89bed229c598.png)
In procedure 2, the path of the folder had been decided to "Advanced topic" and there is no way to create folder within a switcher(include official one).
So, in that case, "Advanced topic/insider creators" is the file path that I want to create if I typed "advanced topic/insider creators".

**Comment by darlal** [comment]
Thanks for the explanation. It seems like what you're asking is to be able to create sub-folders in the Vault from the Switcher. This capability is not supported in the builtin Switcher either. I will think through this as a feature request. Thanks!

**Comment by darlal** [comment]
This capability now exists in the builtin switcher. I will close this issue out. Thanks.

**Comment by darlal** [comment]
This capability now exists in the builtin switcher. I will close this issue out. Thanks.
