### ISSUE TITLE
Create Settings Toggle for hidePathIfRoot

### ISSUE THREAD

**Issue by simudevo** [darlal/obsidian-switcher-plus#75]
Because I noticed the headings view wouldn't list the title of a note if it was in root, I delved into the code to find a way to have notes that were in the vault's root folder have their path shown. I discovered the `hidePathIfRoot` option in the code. I simply changed its value from true to false in the static `defaults()` function to get the behavior I wanted. I think it should be given a setting so that it can be set by the user.

**Comment by darlal** [comment]
@simudevo thanks for the feedback. 

The settings values get serialized to `data.json` file in the plugin directory. So you can just change it there in the mean time and not have to maintain a separate patch/build (if that's what you are doing) until a setting is added in the preference pane.

**Comment by darlal** [comment]
This would be a pretty straight forward PR if you or anyone else 🙂 want to contribute. 

A new toggle setting would needs to be added to [generalSettingsTabSection.ts](https://github.com/darlal/obsidian-switcher-plus/blob/master/src/settings/generalSettingsTabSection.ts) pointing to the `hidePathIfRoot` setting. Add/update some test like in [generalSettingsTabSection.test.ts](https://github.com/darlal/obsidian-switcher-plus/blob/master/src/settings/__tests__/generalSettingsTabSection.test.ts). There are some examples in the codebase for doing this already 🙂

**Comment by darlal** [comment]
This is live with [release 2.3.4](https://github.com/darlal/obsidian-switcher-plus/releases/tag/2.3.4) thanks!
