### ISSUE TITLE
Feature request: Recent commands

### ISSUE THREAD

**Issue by danrthompson** [darlal/obsidian-switcher-plus#76]
Hey! Thanks SO much for this plugin. It is absolutely awesome and I really appreciate that you've generously donated your time to make something really cool for everyone :). 

I was trying out the other alternative command palette today and basically I can say with certainty this your plugin reigns supreme!

That said, there was ONE really awesome feature with the other palette (the plugin is called `Better Command Palette`). It remembers recent commands that you've used and temporarily bumps them to the top.

This is a super useful feature, both to help you remember that command you used 30 mins ago. But also because if you used a command recently it's pretty likely that you'll be using it again soon.

So if you agree that this would be useful, that would be an awesome addition to this plugin. But even if you don't have the time, it's still totally awesome and thanks again :)

**Comment by darlal** [comment]
Hey @danrthompson glad you're finding Switcher++ useful. Thanks for the feature request, I'll add it to the backlog.

**Comment by darlal** [comment]
@danrthompson this is live as of [release 2.3.2](https://github.com/darlal/obsidian-switcher-plus/releases/tag/2.3.2), thanks!

**Comment by danrthompson** [comment]
@darlal thanks so much!! I switched from better command palette to quick switcher++ as a result!! Definitely the best command palette now
