### ISSUE TITLE
Default to open in new tab switch doesn't work for me in either mobile or desktop

### ISSUE THREAD

**Issue by Randy-Astle** [darlal/obsidian-switcher-plus#77]
Either there is something I don't understand or have configured correctly, or... there is a bug. :-O 

On both desktop (Windows) and mobile (Android), I have "Default to open in a new tab" switch enabled. In both environments, when I find a note, and select it, it always opens in the active tab.

**Comment by Gewerd-Strauss** [comment]
I am already unhappy about the update because tabs don't really work well imo -  I'd rather use splitpane maximise a view, but that isn't really an option now, but I guess I will adapt somehow. However, I would greatly appreciate this to be fixed, as it would alleviate a lot of the friction I am all of a sudden dealing with.

**Comment by darlal** [comment]
Sorry it seems to be misbehaving. Let's try to figure out what is going on. @Randy-Astle it would be helpful if you could provide the exact steps that you are taking that results in that behavior.

1. Open the developer console while running through your steps. Any errors that happen should be logged to the console. Please report back if you see any errors
2. What mode is Switcher++ in when it doesn't work as expected? for example `Headings mode`, `Editor mode`, etc..

**Comment by Randy-Astle** [comment]
Attached is an image of how I have Quick Switcher configured.

Note that all the mode triggers are the character followed by a space.

My steps:
1. Open Quick Switcher++ with my keyboard shortcut (CTRL + O)
2. Type the search terms
3. Either click on the note entry or select it and press enter
4. In both cases, the contents of the currently active tab are replaced with the selected note

Interesting:
When I open the Developer Console, 16 errors already exist (the image is attached). While stepping through the process of using Quick Switcher to open a new file (with either a click or ENTER), no new errors appear.

---

Also, now that we have tabs and panes (tab groups) perhaps the option can be refined to support opening the note in a new tab in the same pane or a new tab in a new pane?

Randy

![QuickSwitcher Settings](https://user-images.githubusercontent.com/1444205/195987485-c6ce8e71-2ce9-47b2-83a5-8eccffbc19f4.png)

![Developer Console Errors](https://user-images.githubusercontent.com/1444205/195988288-9369957d-90e9-43aa-ae36-f6714338bdac.png)

**Comment by Randy-Astle** [comment]
I reinstalled Obsidian to see if that would eliminate the 16 errors when I opened the Developer Console.

Now there is only one error (image attached). However, notes still replace the contents of the current tab when selected in Quick Switcher++.

Randy

![Errors after reinstalling](https://user-images.githubusercontent.com/1444205/195990611-71d1f738-5aa3-4c09-b823-3d753d21a341.png)

**Comment by darlal** [comment]
So those errors are not related to Switcher++ at all. It looks like the sources of those errors are:

1. obsidian-vault-statistics-plugin - this looks like the source of most of the errors. You should consider reporting those to the plugin author
2. Obsidian sync - this looks like normal obsidian sync errors when you go offline
3. obsidian-file-heading-sync - some errors from this plugin as well

Try this: 

1. Execute the `Quick Switcher++: Open in Headings Mode` command using the command palette
2. Search for a file that is **not** already open in an editor
3. Select that file and open it

I think that this will open the file in a new tab with the behavior you are expecting. I think what's happening is that you are using the `Quick Switcher++: Open` command with the shortcut you have mapped. This opens the switcher in `Standard` mode, which is the out of the box, plain Obsidian system functionality. Almost all of the custom Switcher++ functionality isn't support in `Standard` mode. This is by design, but a common source of confusion, something I should think about.

**Comment by Gewerd-Strauss** [comment]
I can confirm that the steps 

> Execute the Quick Switcher++: Open in Headings Mode command using the command palette
> Search for a file that is not already open in an editor
> Select that file and open it

will resolve this issue. Hence, I will be remapping
Regarding the mapping, I personally don't really see the need for a standard mode which mirrors obsidian's build-in by artificially restricting the plugins capabilities. If that were the case, users can either 
- just not use this plugin and keep the default one
- or assign a hotkey to the native switcher

Either way, functionally there is little reason to mirror obsidian's build-in switcher, and even less reason to make it the default. It's already there & covered by native code, no need to reinvent the wheel in a seemingly identical manner.

This won't be an issue for those who read the documentation properly (as I should have done, admittedly), but it does generate confusion among those who did not do so, or who simply forgot.

**Comment by Randy-Astle** [comment]
Interesting...

If I use one of the modes (in my case, triggered it with the characters) the note I select opens in a new tab.

I like standard mode when I search for files (my most common use case). I also like the modal searches -- specific scenarios that are sometimes exactly what I want. However, I assumed that standard mode for Quick Switcher++ still supported any other applicable configuration options (e.g. opening in a new tab).

IMO, triggering modes with keyboard shortcuts or with one or more leading characters is pure genius. I chose to select the mode with the characters (and a trailing space - better visual separation and unlikely to be accidentally part of my search) and using just one keyboard shortcut to launch Quick Switcher++ (Which allows me to use those potential shortcuts for other features.)

By default, in standard mode, the list with no search terms is a list of recent files -- another nice feature (though I would like to be able to increase the number of files displayed).

For me, just adding support for standard mode for opening in a new tab (and any other applicable settings -- potentially open in new pane?) will be perfect! :-)

Randy

**Comment by darlal** [comment]
> It's already there & covered by native code, no need to reinvent the wheel in a seemingly identical manner.

@Gewerd-Strauss Switcher++ does not re-implement this functionality, it "inherits" it for free™ from the system switcher. It was an explicit design choice, thinking was you'd get best of both worlds, custom functionality and all system feature that exist today **and in the future**. Switcher++ has evolved to become more feature rich and now could serve as a full replacement.

> By default, in standard mode, the list with no search terms is a list of recent files

@Randy-Astle `Headings mode` does this as well (along with currently open editors).

As I mentioned, this is a common cause of confusion and something I will be putting some thought into. Thanks!

**Comment by Randy-Astle** [comment]
Thanks!
This has been a good discussion -- it helped clarify my understanding of how Quick Switcher++ works.

FYI: I'm going to disable the default open in new tab switch. I'll just use the appropriate keyboard chords to open the note where I want it opened (consistent with the Obsidian's design).

Randy

**Comment by darlal** [comment]
Glad it was helpful!

**Comment by darlal** [comment]
Note: with [release 2.3.0](https://github.com/darlal/obsidian-switcher-plus/releases/tag/2.3.0) the custom functionality is now supported in `Standard` mode too.
