### ISSUE TITLE
Creating new note option should always exist if no exact match for note name found

### ISSUE THREAD

**Issue by tonyxiao** [darlal/obsidian-switcher-plus#79]
I wanted to create a note called `Evergreen`, but it was alas not possible.

![CleanShot 2022-11-01 at 22 08 42@2x](https://user-images.githubusercontent.com/696842/199341959-85e621d6-30b7-41f3-83f9-4d848b8dd059.png)

**Comment by tonyxiao** [comment]
For others in future, there is a workaround using keyboard shortcut `Shift+Enter` will always create the exact note. 
![CleanShot 2022-11-03 at 12 24 17@2x](https://user-images.githubusercontent.com/696842/199708884-c600a164-48c7-4ee4-84cd-f65b204f1600.png)

**Comment by darlal** [comment]
@tonyxiao glad you go it figured out. This is the way it is designed to work, and matches the Obsidian system switcher. Thanks!
