### ISSUE TITLE
bug: symbol and editor modes do not work

### ISSUE THREAD

**Issue by manogna4** [darlal/obsidian-switcher-plus#8]
I upgraded to obsidian 0.9.20 today and noticed that the symbol and editor modes do not work anymore. It was working on 0.9.17 yesterday.

**Comment by darlal** [comment]
yea I'm aware. It's due to major breaking api changes introduced in 9.20. I'm working on it. If you are on the discord you can follow the [conversation](https://discord.com/channels/686053708261228577/707816848615407697/783843553465991178) there.

**Comment by darlal** [comment]
Quick update.. some new APIs released in 0.9.21 should get us back in business. Aiming to have a plugin update out soon.

**Comment by manogna4** [comment]
great. The plug-in breaking has made me realize how much it was part of my
workflow. So I am glad this is getting fixed!

**Comment by darlal** [comment]
Glad you find it useful! I can't navigate without it 😅

I just pushed an update that has 0.9.20 compatibility (also tested in 0.9.22), so it should be working again 😄 

You can updated via the "Check for updates" button in the Obsidian prefs panel (Third-party plugins section).

**Comment by manogna4** [comment]
I see it working 👍
