### ISSUE TITLE
Dataview query support

### ISSUE THREAD

**Issue by tonyxiao** [darlal/obsidian-switcher-plus#80]
I have a dataview like this

```dataview
TABLE
WHERE startswith(file.name, "Project ")
LIMIT 5
```

I'd love to be able to bind a switcher plus command to it to allow me to quickly open any projects defined by the dataview query.

**Comment by darlal** [comment]
Hey @tonyxiao that's an interesting idea, kind of like an interactive, filtering frontend for Dataview. It's probably out of scope for Switcher++ for the time being. I would definitely recommend proposing the idea to the Dataview authors - or maybe even as a separate Dataview focused plugin. Thanks for sharing, I like the idea!
