### ISSUE TITLE
Feature request: Search for tags

### ISSUE THREAD

**Issue by tonyxiao** [darlal/obsidian-switcher-plus#81]
The tag pane doesn't have the ability to filter for tags based on keywords. It would be amazing if switcher plus had a way to let me filter for tags based on keywords!

**Comment by tonyxiao** [comment]
For those looking I found an alternative that works for this scenario. https://github.com/AlexBieg/obsidian-better-command-palette#file-searching-using-tags

**Comment by darlal** [comment]
There's also another pluglin called [Another Quick Switcher](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher) that also provides tag search functionality.

All three of these plugins can be installed and used at the same time. So you can mix and match for specific functionality that you care about for all your quick switching needs.
