### ISSUE TITLE
Add Link in editing memo

### ISSUE THREAD

**Issue by ParkJaeSeong** [darlal/obsidian-switcher-plus#82]
Thanks for making a great plugin. It's always been great to use when exploring notes. It's a good replacement for the quick switcher plugin.

I propose to develop one function. When searching for a note, it would be nice to have a function to directly enter a link into the memo currently being edited (together with a shortcut key).

[[memoname]]
[[memoname#heading]]

**Comment by darlal** [comment]
Thanks for the feature request.

**Comment by darlal** [comment]
Hey @ParkJaeSeong this is live in [release 3.3.3](https://github.com/darlal/obsidian-switcher-plus/releases/tag/3.3.3). Thanks!
