### ISSUE TITLE
[BUG] Symbol mode shows outdated data

### ISSUE THREAD

**Issue by tonyxiao** [darlal/obsidian-switcher-plus#83]
The behavior differs between invoking the `open in symbol mode` command directly vs. the `Open` command and then manually typing `@` symbol to invoke the symbol mode. Directly `open in symbol mode` seems to be slightly more reliable, but both approaches appear to show outdated data at some point in time. 

<img style="max-width:300px;" src="https://cdn.loom.com/sessions/thumbnails/a91ca2bd5d644f0ba00e40f9f69b0dc9-with-play.gif">

<a href="https://www.loom.com/share/a91ca2bd5d644f0ba00e40f9f69b0dc9">
    <p>Quick switcher++ symbol mode bug - Watch Video</p>
    <img style="max-width:300px;" src="https://cdn.loom.com/sessions/thumbnails/a91ca2bd5d644f0ba00e40f9f69b0dc9-with-play.gif">
  </a>

**Comment by darlal** [comment]
Thanks for the report. I will look into this.
