### ISSUE TITLE
Ability to search YAML metadata

### ISSUE THREAD

**Issue by fncll** [darlal/obsidian-switcher-plus#85]
It would be awesome to be able to limit a search to YAML metadata in some way. Not sure if this is possible or not! Thanks in advance for your consideration.

**Comment by darlal** [comment]
Hey @fncll could you describe a bit more about what you are thinking here, and what you'd like to be able to do?

**Comment by fncll** [comment]
I have many files with YAML headers, such as this:

```
---
title: War
author: Charles Simic
author-sort: Simic, Charles
author-sex: M
poem-type: traditional
original-year: 1992
published: Y
date: 2023-12-10
pub-number: 00037
pub-subject: 00037 ◊ War ◊ Charles Simic
embedded-title: false
---
```

It would be great if there were a way to search that data specifically. Perhaps by using a query with a colon `published: Y` or some other way.

**Comment by darlal** [comment]
It sound like you're looking for a vault wide frontmatter search, is that right? Have you seen the [Omnisearch plugin](https://github.com/scambier/obsidian-omnisearch), does that kind of a full text search fulfill your needs?

**Comment by fncll** [comment]
Ah, that does work, basically. Thanks!
