### ISSUE TITLE
[FR] Add Outgoing Links to Related Items

### ISSUE THREAD

**Issue by zcysxy** [darlal/obsidian-switcher-plus#87]
Searching Related Items is a killer feature! Now it can search backlinks; it would be better if it can also search outgoing links. Then it can serve as a way to search in the local graph.

**Comment by darlal** [comment]
Adding outgoing links was always part of the plan, coming soon. Thanks!

**Comment by darlal** [comment]
Hey @zcysxy this feature is live with [release 2.3.3](https://github.com/darlal/obsidian-switcher-plus/releases/tag/2.3.3). Thanks!

**Comment by zcysxy** [comment]
Thank you so much!
