### ISSUE TITLE
[Bug] Navigating to Links puts cursor at end of block

### ISSUE THREAD

**Issue by liamcain** [darlal/obsidian-switcher-plus#9]
**Plugin Version:** 0.0.9
**Obsidian version:** 0.10.7

## Steps to reproduce

- Open Switcher in Symbol mode
- select a 🔗 link

## Expected?

I would expect the cursor to appear over the link (preferably at the start of the link).

## Actual

Instead, the cursor appears at the end of the block that the link appears in.

**Comment by darlal** [comment]
I would expect the same. Fixed. Please hit that update button 🙂

**Comment by liamcain** [comment]
Works beautifully, thanks! ✨

**Comment by liamcain** [comment]
Actually, just to be super nitpicky, maybe it should move the cursor over 2 characters (past the `[[`) for links? That way I can immediately press ctrl+enter to navigate into the link? What do you think?

**Comment by darlal** [comment]
Navigation currently doesn't take into account the "type" of symbol, so it just drops you at the beginning of the range. For example links would be 2 characters `[[` as you said, but embeds would be 3 `![[`, tags 1 `#`, headers variable 1-6 `#...#` if it were to be applied consistently across all symbols. I'll give it some thought. Thanks!

**Comment by liamcain** [comment]
Oh, great point. I clearly didn't put too much thought into it. That's probably not worth it then since I can just get there with an extra keystroke or 2.
