### ISSUE TITLE
Can't search notes that begin with "+"

### ISSUE THREAD

**Issue by Elaws** [darlal/obsidian-switcher-plus#90]
# Problem description

Following [Bryan Jenks workflow](https://youtube.com/watch?v=wB89lJs5A3s), some of my notes begin by the symbol "+" to indicate a note type. Using Obsidian quick switcher, I could quickly filter these notes by beginning my query with the "+" symbol.

This is not possible in Quick switcher plus because "+" is reserved to a special search.

# Possible solution

Is it possible to change "+" symbol to another one ? Or to disable this option ?

Thank you

**Comment by darlal** [comment]
Hey @Elaws it is possible to change the trigger character for each of the modes. [Workspace mode](https://github.com/darlal/obsidian-switcher-plus#switch-workspaces) uses the `+` trigger by default, but you can change this in the settings.

<img width="622" alt="image" src="https://user-images.githubusercontent.com/5191776/205442461-ee7bcf78-727c-40fa-8da3-6cdaf60c5862.png">
