### ISSUE TITLE
FR for workspace list mode: create a new workspace if the term entered doesn't match an existing workspace

### ISSUE THREAD

**Issue by Randy-Astle** [darlal/obsidian-switcher-plus#94]
While reviewing and modifying my settings for switcher plus, it occurred to me that it would be convenient if I could save the existing layout as a new workspace by pressing ENTER if the word or phrase didn't match an existing workspace name.

**Comment by darlal** [comment]
Thanks for the FR! yes, this can be added. There's also a more full-feature workspace manager plugin available as well [obsidian-workspaces-plus](https://github.com/nothingislost/obsidian-workspaces-plus).

**Comment by darlal** [comment]
This is live with [release 3.3.8](https://github.com/darlal/obsidian-switcher-plus/releases/tag/3.3.8). Thanks!
