### ISSUE TITLE
Ctrl+Alt+Enter doesn't create new note to right if there are suggestions found

### ISSUE THREAD

**Issue by trainbuffer** [darlal/obsidian-switcher-plus#96]
QuickSwitcher++'s "Open in Standard Mode" ->
Start typing the name of a **new** note I want to create ->
- If no suggestions are found `Ctrl+Alt+Enter` creates the new note to the right (new tab group) as expected.
- If suggestions are found and I hit `Ctrl+Alt+Enter`, my new note name is ignored, and the first suggestion in the list is opened to the right. 

Not sure if this is a bug or setting that needs changing. Thanks! 

**Environment:**
Windows11; Obsidian 1.1.9 (1.1.9 installer), QuickSwitcherPlus 2.3.7, Sandbox with only QuickSwithcerPlus installed

**Comment by darlal** [comment]
I believe this is expected behavior, the builtin, system switcher behaves the same way. The create shortcut is `shift+enter`, and `cmd+shift+enter` (`ctrl+shift+enter` on Windows I think, I don't have access to a Windows system) to create to the right. Thanks!
