### ISSUE TITLE
[Feature Request] Add Files in Sidebar to Editor List Mode

### ISSUE THREAD

**Issue by julroger2013** [darlal/obsidian-switcher-plus#99]
I've noticed that I can select most of my sidebar panes—such as, for instance, custom frames or the tag pane—from Editor List Mode. However, I have realized that normal Obsidian .md notes that I might choose to place in the sidebar don't appear in Editor List Mode, although any notes that are open in the center panes _do_ appear on the list. 

Would it be possible to make it so that all open .md notes appear in the Editor List Mode, regardless of whether they are in the sidebar or center panes?

**Comment by darlal** [comment]
Hey @julroger2013 this is already supported and should work. The [Include side panel views](https://github.com/darlal/obsidian-switcher-plus#editor-navigation-configuration) setting in the "Editor List Mode" section controls which side panel view types may appear in the result list. Take a look at that setting and ensure that the list contains `markdown` to get the behavior you're looking for. Let me know if it's not working for you.

<img width="774" alt="image" src="https://user-images.githubusercontent.com/5191776/227721367-eb8e59bf-1fd4-4c3f-be60-57f5749560a7.png">

**Comment by julroger2013** [comment]
Haha, thank you! Yes, that worked perfectly. 

I feel quite foolish—I even described the files to you as "markdown" files yet somehow didn't realize that "markdown" was the appropriate side panel view to include. 

Thank you for your help!

**Comment by darlal** [comment]
No worries at all, I'm glad we got it figured out 🙂
